class Generator
SAMPLE_USERS = [{"profile"=>
   {"username"=>"achiu",
    "fullname"=>"Arthur Chiu",
    "location"=>"Irvine, CA",
    "email"=>"achiu@github.com",
    "link"=>"http://arthurchiu.com",
    "join_date"=>"2008-09-16T03:24:44Z"},
  "stats"=>
   {"VimL"=>{"count"=>1, "star"=>2},
    "Ruby"=>{"count"=>26, "star"=>1209},
    "JavaScript"=>{"count"=>1, "star"=>5}}},
 {"profile"=>
   {"username"=>"adelcambre",
    "fullname"=>"Andy Delcambre",
    "location"=>"San Francisco, CA",
    "email"=>"adelcambre@gmail.com",
    "link"=>"http://andy.delcambre.com/",
    "join_date"=>"2008-02-13T18:43:41Z"},
  "stats"=>
   {"CSS"=>{"count"=>1, "star"=>1},
    "Ruby"=>{"count"=>26, "star"=>55},
    "JavaScript"=>{"count"=>3, "star"=>8},
    "Shell"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"aden",
    "fullname"=>"Aden Beihl",
    "location"=>"aden@github.com",
    "email"=>"Joined on Feb 27, 2012",
    "link"=>"",
    "join_date"=>"2012-02-27T21:55:19Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"alysonla",
    "fullname"=>"Alyson La",
    "location"=>"San Francisco, CA",
    "email"=>"alyson@github.com",
    "link"=>"Joined on Oct 22, 2012",
    "join_date"=>"2012-10-22T17:14:54Z"},
  "stats"=>
   {"Ruby"=>{"count"=>2, "star"=>0},
    "CSS"=>{"count"=>4, "star"=>7},
    "JavaScript"=>{"count"=>3, "star"=>18},
    "PHP"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"amateurhuman",
    "fullname"=>"Chris Kelly",
    "location"=>"San Francisco, CA",
    "email"=>"amateurhuman@gmail.com",
    "link"=>"http://amateurhuman.com",
    "join_date"=>"2010-08-24T05:42:02Z"},
  "stats"=>
   {"Ruby"=>{"count"=>2, "star"=>2},
    "VimL"=>{"count"=>1, "star"=>9},
    "CoffeeScript"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"ammeep",
    "fullname"=>"Amy Palamountain",
    "location"=>"New Zealand",
    "email"=>"amy@github.com",
    "link"=>"http://amy.palamounta.in",
    "join_date"=>"2011-09-04T01:16:52Z"},
  "stats"=>
   {"CSS"=>{"count"=>3, "star"=>11},
    "C#"=>{"count"=>3, "star"=>25},
    "JavaScript"=>{"count"=>2, "star"=>3}}},
 {"profile"=>
   {"username"=>"antonio",
    "fullname"=>"Antonio Santos",
    "location"=>"Huelva, Spain",
    "email"=>"http://www.santosvelasco.com",
    "link"=>"Joined on Jul 19, 2008",
    "join_date"=>"2008-07-19T10:01:20Z"},
  "stats"=>
   {"Ruby"=>{"count"=>4, "star"=>7},
    "Shell"=>{"count"=>3, "star"=>1},
    "VimL"=>{"count"=>1, "star"=>1},
    "Lua"=>{"count"=>2, "star"=>1},
    "Python"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"arfon",
    "fullname"=>"Arfon Smith",
    "location"=>"Chicago",
    "email"=>"arfon.smith@gmail.com",
    "link"=>"http://arfon.org",
    "join_date"=>"2008-04-03T11:05:32Z"},
  "stats"=>
   {"TeX"=>{"count"=>4, "star"=>1},
    "C"=>{"count"=>1, "star"=>0},
    "CSS"=>{"count"=>1, "star"=>0},
    "Ruby"=>{"count"=>14, "star"=>20},
    "Java"=>{"count"=>1, "star"=>0},
    "JavaScript"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"aroben",
    "fullname"=>"Adam Roben",
    "location"=>"Swarthmore, PA",
    "email"=>"adam@roben.org",
    "link"=>"Joined on Jul 15, 2011",
    "join_date"=>"2011-07-15T15:32:24Z"},
  "stats"=>
   {"Ruby"=>{"count"=>2, "star"=>1},
    "JavaScript"=>{"count"=>4, "star"=>18},
    "PowerShell"=>{"count"=>1, "star"=>7},
    "Objective-C"=>{"count"=>2, "star"=>5},
    "Shell"=>{"count"=>1, "star"=>3},
    "C"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"arrbee",
    "fullname"=>"Russell Belfer",
    "location"=>"San Francisco, CA",
    "email"=>"rb@github.com",
    "link"=>"Joined on Jul 9, 2009",
    "join_date"=>"2009-07-09T18:23:04Z"},
  "stats"=>
   {"Python"=>{"count"=>1, "star"=>0},
    "C"=>{"count"=>2, "star"=>26},
    "Shell"=>{"count"=>1, "star"=>6},
    "JavaScript"=>{"count"=>1, "star"=>3}}},
 {"profile"=>
   {"username"=>"atmos",
    "fullname"=>"Corey Donohoe",
    "location"=>"Potrero, SF",
    "email"=>"atmos@atmos.org",
    "link"=>"http://www.atmos.org",
    "join_date"=>"2008-01-22T09:14:11Z"},
  "stats"=>
   {"CoffeeScript"=>{"count"=>6, "star"=>893},
    "Ruby"=>{"count"=>57, "star"=>757},
    "Objective-C"=>{"count"=>2, "star"=>6},
    "Go"=>{"count"=>1, "star"=>3},
    "Lua"=>{"count"=>1, "star"=>3},
    "C++"=>{"count"=>1, "star"=>3},
    "Shell"=>{"count"=>4, "star"=>31},
    "JavaScript"=>{"count"=>14, "star"=>110},
    "Perl"=>{"count"=>1, "star"=>8}}},
 {"profile"=>
   {"username"=>"azizshamim",
    "fullname"=>"Aziz Shamim",
    "location"=>"Nashville, TN",
    "email"=>"http://github.com",
    "link"=>"Joined on Oct 24, 2008",
    "join_date"=>"2008-10-24T03:17:37Z"},
  "stats"=>
   {"CSS"=>{"count"=>1, "star"=>0},
    "Ruby"=>{"count"=>1, "star"=>0},
    "JavaScript"=>{"count"=>2, "star"=>4}}},
 {"profile"=>
   {"username"=>"balevine",
    "fullname"=>"Brian Levine",
    "location"=>"Jersey City, NJ",
    "email"=>"balevine@github.com",
    "link"=>"Joined on Sep 27, 2012",
    "join_date"=>"2012-09-27T02:52:04Z"},
  "stats"=>
   {"CSS"=>{"count"=>2, "star"=>0},
    "Shell"=>{"count"=>1, "star"=>5},
    "JavaScript"=>{"count"=>1, "star"=>6}}},
 {"profile"=>
   {"username"=>"benbalter",
    "fullname"=>"Ben Balter",
    "location"=>"Washington, DC",
    "email"=>"ben.balter@github.com",
    "link"=>"http://ben.balter.com",
    "join_date"=>"2010-05-20T20:38:33Z"},
  "stats"=>
   {"HTML"=>{"count"=>1, "star"=>40},
    "Ruby"=>{"count"=>34, "star"=>1012},
    "PHP"=>{"count"=>23, "star"=>1007},
    "Shell"=>{"count"=>4, "star"=>148},
    "CSS"=>{"count"=>13, "star"=>102},
    "CoffeeScript"=>{"count"=>7, "star"=>2},
    "JavaScript"=>{"count"=>18, "star"=>46},
    "Awk"=>{"count"=>1, "star"=>21}}},
 {"profile"=>
   {"username"=>"benogle",
    "fullname"=>"Ben Ogle",
    "location"=>"ogle.ben@gmail.com",
    "email"=>"http://benogle.com",
    "link"=>"Joined on Apr 1, 2009",
    "join_date"=>"2009-04-01T00:53:31Z"},
  "stats"=>
   {"CoffeeScript"=>{"count"=>6, "star"=>2},
    "CSS"=>{"count"=>1, "star"=>3},
    "JavaScript"=>{"count"=>7, "star"=>15},
    "Ruby"=>{"count"=>2, "star"=>2},
    "Python"=>{"count"=>4, "star"=>6},
    "C#"=>{"count"=>1, "star"=>4}}},
 {"profile"=>
   {"username"=>"bernars",
    "fullname"=>"Sheri Bernard",
    "location"=>"United States",
    "email"=>"bernars@github.com",
    "link"=>"https://twitter.com/shegoesbysheri",
    "join_date"=>"2013-08-14T03:59:10Z"},
  "stats"=>{"CSS"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"bhuga",
    "fullname"=>"Ben Lavender",
    "location"=>"New Orleans, LA",
    "email"=>"blavender@gmail.com",
    "link"=>"https://bhuga.net",
    "join_date"=>"2008-06-05T08:02:36Z"},
  "stats"=>
   {"Ruby"=>{"count"=>30, "star"=>236},
    "HTML"=>{"count"=>1, "star"=>1},
    "Python"=>{"count"=>2, "star"=>0},
    "JavaScript"=>{"count"=>6, "star"=>11},
    "VimL"=>{"count"=>1, "star"=>2},
    "Objective-C"=>{"count"=>1, "star"=>4},
    "CoffeeScript"=>{"count"=>2, "star"=>3},
    "PHP"=>{"count"=>2, "star"=>3}}},
 {"profile"=>
   {"username"=>"bigred",
    "fullname"=>"Lara K Owen",
    "location"=>"San Francisco, CA",
    "email"=>"lara.owen@github.com",
    "link"=>"Joined on Sep 3, 2013",
    "join_date"=>"2013-09-03T17:30:46Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"bkeepers",
    "fullname"=>"Brandon Keepers",
    "location"=>"Holland, MI, US",
    "email"=>"bkeepers@github.com",
    "link"=>"http://opensoul.org",
    "join_date"=>"2008-02-09T16:42:49Z"},
  "stats"=>
   {"HTML"=>{"count"=>1, "star"=>3},
    "CoffeeScript"=>{"count"=>3, "star"=>175},
    "Ruby"=>{"count"=>17, "star"=>823},
    "JavaScript"=>{"count"=>7, "star"=>1290},
    "Shell"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"bleikamp",
    "fullname"=>"Ben Bleikamp",
    "location"=>"California",
    "email"=>"ben@bleikamp.com",
    "link"=>"http://bleikamp.com",
    "join_date"=>"2008-09-22T20:28:53Z"},
  "stats"=>
   {"CoffeeScript"=>{"count"=>2, "star"=>14},
    "Ruby"=>{"count"=>1, "star"=>12}}},
 {"profile"=>
   {"username"=>"bnferguson",
    "fullname"=>"Brandon Ferguson",
    "location"=>"Joined on Jan 19, 2009",
    "email"=>"",
    "link"=>"",
    "join_date"=>"2009-01-19T18:52:25Z"},
  "stats"=>
   {"CSS"=>{"count"=>1, "star"=>0},
    "JavaScript"=>{"count"=>1, "star"=>1},
    "Arduino"=>{"count"=>2, "star"=>2},
    "VimL"=>{"count"=>1, "star"=>0},
    "Ruby"=>{"count"=>2, "star"=>2},
    "Java"=>{"count"=>3, "star"=>2}}},
 {"profile"=>
   {"username"=>"briandoll",
    "fullname"=>"Brian Doll",
    "location"=>"San Francisco, CA",
    "email"=>"briandoll@github.com",
    "link"=>"http://emphaticsolutions.com",
    "join_date"=>"2008-04-03T18:45:16Z"},
  "stats"=>
   {"VimL"=>{"count"=>2, "star"=>47},
    "JavaScript"=>{"count"=>4, "star"=>2},
    "CSS"=>{"count"=>3, "star"=>4},
    "CoffeeScript"=>{"count"=>1, "star"=>0},
    "Ruby"=>{"count"=>18, "star"=>241},
    "Shell"=>{"count"=>1, "star"=>6}}},
 {"profile"=>
   {"username"=>"brianmario",
    "fullname"=>"Brian Lopez",
    "location"=>"San Francisco, Ca",
    "email"=>"seniorlopez@gmail.com",
    "link"=>"https://twitter.com/brianmario",
    "join_date"=>"2008-05-26T22:54:55Z"},
  "stats"=>
   {"Ruby"=>{"count"=>18, "star"=>693},
    "C"=>{"count"=>8, "star"=>553},
    "JavaScript"=>{"count"=>3, "star"=>51},
    "Perl"=>{"count"=>1, "star"=>10}}},
 {"profile"=>
   {"username"=>"brianna4",
    "fullname"=>"Brianna Fore",
    "location"=>"San Francisco",
    "email"=>"brianna.fore@github.com",
    "link"=>"Joined on May 13, 2013",
    "join_date"=>"2013-05-13T17:23:49Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"brntbeer",
    "fullname"=>"Brent Beer",
    "location"=>"San Francisco, CA",
    "email"=>"brentbeer@github.com",
    "link"=>"http://github.com/brntbeer",
    "join_date"=>"2009-01-08T18:51:00Z"},
  "stats"=>
   {"CSS"=>{"count"=>5, "star"=>0},
    "Shell"=>{"count"=>2, "star"=>8},
    "Ruby"=>{"count"=>10, "star"=>16},
    "Groovy"=>{"count"=>1, "star"=>3},
    "JavaScript"=>{"count"=>6, "star"=>10},
    "Objective-C"=>{"count"=>1, "star"=>0},
    "C++"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"buckelij",
    "fullname"=>"Elijah Buck",
    "location"=>"WA",
    "email"=>"Joined on Aug 20, 2010",
    "link"=>"",
    "join_date"=>"2010-08-20T16:33:48Z"},
  "stats"=>
   {"Python"=>{"count"=>2, "star"=>0},
    "Shell"=>{"count"=>2, "star"=>0},
    "PowerShell"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"Caged",
    "fullname"=>"Justin Palmer",
    "location"=>"Portland, OR",
    "email"=>"justin@labratrevenge.com",
    "link"=>"http://labratrevenge.com",
    "join_date"=>"2008-01-15T04:47:24Z"},
  "stats"=>
   {"Shell"=>{"count"=>4, "star"=>1},
    "JavaScript"=>{"count"=>18, "star"=>570},
    "Makefile"=>{"count"=>1, "star"=>47},
    "R"=>{"count"=>1, "star"=>0},
    "CSS"=>{"count"=>1, "star"=>1},
    "CoffeeScript"=>{"count"=>3, "star"=>22},
    "Python"=>{"count"=>2, "star"=>2},
    "Ruby"=>{"count"=>14, "star"=>212},
    "Objective-C"=>{"count"=>5, "star"=>337},
    "C"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"cameronmcefee",
    "fullname"=>"Cameron McEfee",
    "location"=>"San Francisco",
    "email"=>"cameron@github.com",
    "link"=>"http://www.cameronmcefee.com",
    "join_date"=>"2009-04-12T06:16:59Z"},
  "stats"=>
   {"JavaScript"=>{"count"=>3, "star"=>54},
    "CoffeeScript"=>{"count"=>1, "star"=>1},
    "CSS"=>{"count"=>1, "star"=>58},
    "Python"=>{"count"=>1, "star"=>6}}},
 {"profile"=>
   {"username"=>"charliesome",
    "fullname"=>"Charlie Somerville",
    "location"=>"Melbourne, Australia",
    "email"=>"charlie@charlie.bz",
    "link"=>"https://charlie.bz",
    "join_date"=>"2010-01-09T14:49:23Z"},
  "stats"=>
   {"JavaScript"=>{"count"=>5, "star"=>308},
    "Ruby"=>{"count"=>41, "star"=>1088},
    "C"=>{"count"=>22, "star"=>862},
    "Objective-C++"=>{"count"=>1, "star"=>3},
    "Perl6"=>{"count"=>1, "star"=>0},
    "Python"=>{"count"=>1, "star"=>2},
    "Rust"=>{"count"=>2, "star"=>1},
    "CSS"=>{"count"=>1, "star"=>5},
    "Haskell"=>{"count"=>2, "star"=>3},
    "Objective-C"=>{"count"=>3, "star"=>8},
    "C++"=>{"count"=>4, "star"=>5},
    "Shell"=>{"count"=>4, "star"=>24},
    "VimL"=>{"count"=>1, "star"=>2},
    "Slash"=>{"count"=>1, "star"=>2},
    "PHP"=>{"count"=>3, "star"=>147},
    "C#"=>{"count"=>1, "star"=>1},
    "Assembly"=>{"count"=>1, "star"=>6}}},
 {"profile"=>
   {"username"=>"chrishunt",
    "fullname"=>"Chris Hunt",
    "location"=>"Portland, Oregon",
    "email"=>"c@chrishunt.co",
    "link"=>"http://www.chrishunt.co",
    "join_date"=>"2009-03-20T17:19:16Z"},
  "stats"=>
   {"VimL"=>{"count"=>2, "star"=>491},
    "Shell"=>{"count"=>3, "star"=>4},
    "Ruby"=>{"count"=>30, "star"=>1478},
    "JavaScript"=>{"count"=>6, "star"=>206},
    "CSS"=>{"count"=>5, "star"=>22},
    "Java"=>{"count"=>8, "star"=>3}}},
 {"profile"=>
   {"username"=>"chrissiebrodigan",
    "fullname"=>"Chrissie Brodigan",
    "location"=>"San Francisco",
    "email"=>"http://chrissiebrodigan.com",
    "link"=>"Joined on Jun 29, 2010",
    "join_date"=>"2010-06-29T13:03:35Z"},
  "stats"=>
   {"JavaScript"=>{"count"=>1, "star"=>0}, "PHP"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"ciaramcguire",
    "fullname"=>"Ciara McGuire",
    "location"=>"Dublin",
    "email"=>"Joined on Sep 21, 2012",
    "link"=>"",
    "join_date"=>"2012-09-21T15:07:55Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"cobyism",
    "fullname"=>"Coby Chapple",
    "location"=>"Belfast, UK",
    "email"=>"coby@github.com",
    "link"=>"http://cobyism.com",
    "join_date"=>"2010-06-04T09:58:36Z"},
  "stats"=>
   {"CSS"=>{"count"=>9, "star"=>632},
    "Shell"=>{"count"=>2, "star"=>37},
    "CoffeeScript"=>{"count"=>7, "star"=>36},
    "JavaScript"=>{"count"=>3, "star"=>5},
    "Ruby"=>{"count"=>7, "star"=>63},
    "Python"=>{"count"=>1, "star"=>1},
    "C"=>{"count"=>1, "star"=>3}}},
 {"profile"=>
   {"username"=>"Coecoe",
    "fullname"=>"Jules Coe Meschan",
    "location"=>"San Francisco, CA",
    "email"=>"jules@github.com",
    "link"=>"Joined on Aug 25, 2013",
    "join_date"=>"2013-08-25T23:19:49Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"connors",
    "fullname"=>"Connor Sears",
    "location"=>"Castro Valley, CA",
    "email"=>"connor@connorsears.com",
    "link"=>"http://connor.town",
    "join_date"=>"2011-06-24T20:08:28Z"},
  "stats"=>
   {"CSS"=>{"count"=>6, "star"=>346}, "JavaScript"=>{"count"=>2, "star"=>15}}},
 {"profile"=>
   {"username"=>"craigreyes",
    "fullname"=>"Craig",
    "location"=>"craig@github.com",
    "email"=>"Joined on Nov 26, 2012",
    "link"=>"",
    "join_date"=>"2012-11-26T18:34:48Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"d2fn",
    "fullname"=>"Dietrich Featherston",
    "location"=>"Oakland",
    "email"=>"d@github.com",
    "link"=>"http://d2fn.com",
    "join_date"=>"2009-03-13T01:06:20Z"},
  "stats"=>
   {"VimL"=>{"count"=>1, "star"=>0},
    "CSS"=>{"count"=>3, "star"=>1},
    "Java"=>{"count"=>9, "star"=>53},
    "JavaScript"=>{"count"=>4, "star"=>3},
    "Processing"=>{"count"=>2, "star"=>0},
    "Go"=>{"count"=>1, "star"=>187},
    "Ruby"=>{"count"=>3, "star"=>99},
    "C"=>{"count"=>1, "star"=>0},
    "Shell"=>{"count"=>1, "star"=>0},
    "C++"=>{"count"=>2, "star"=>2},
    "Scala"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"danishkhan",
    "fullname"=>"Danish Khan",
    "location"=>"San Francisco, CA",
    "email"=>"dk@danishkhan.org",
    "link"=>"http://danishkhan.org",
    "join_date"=>"2008-08-03T21:56:09Z"},
  "stats"=>
   {"CSS"=>{"count"=>1, "star"=>1},
    "Java"=>{"count"=>1, "star"=>0},
    "JavaScript"=>{"count"=>3, "star"=>111},
    "Ruby"=>{"count"=>9, "star"=>20}}},
 {"profile"=>
   {"username"=>"davideg",
    "fullname"=>"David Ginsburg",
    "location"=>"Joined on Sep 11, 2010",
    "email"=>"",
    "link"=>"",
    "join_date"=>"2010-09-11T08:04:42Z"},
  "stats"=>{"Python"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"dbussink",
    "fullname"=>"Dirkjan Bussink",
    "location"=>"Enschede",
    "email"=>"d.bussink@gmail.com",
    "link"=>"http://www.criticalcodes.com",
    "join_date"=>"2008-04-18T19:41:36Z"},
  "stats"=>
   {"C"=>{"count"=>2, "star"=>6},
    "C++"=>{"count"=>1, "star"=>0},
    "Ruby"=>{"count"=>9, "star"=>53}}},
 {"profile"=>
   {"username"=>"defunkt",
    "fullname"=>"Chris Wanstrath",
    "location"=>"San Francisco",
    "email"=>"chris@github.com",
    "link"=>"http://chriswanstrath.com/",
    "join_date"=>"2007-10-20T05:24:19Z"},
  "stats"=>
   {"JavaScript"=>{"count"=>14, "star"=>720},
    "Ruby"=>{"count"=>49, "star"=>3749},
    "CoffeeScript"=>{"count"=>2, "star"=>163},
    "Python"=>{"count"=>3, "star"=>829},
    "Io"=>{"count"=>1, "star"=>27},
    "PHP"=>{"count"=>1, "star"=>3},
    "C"=>{"count"=>3, "star"=>21},
    "Objective-C"=>{"count"=>2, "star"=>10}}},
 {"profile"=>
   {"username"=>"derekgr",
    "fullname"=>"Derek Greentree",
    "location"=>"Boulder, CO",
    "email"=>"derek@github.com",
    "link"=>"Joined on Mar 5, 2009",
    "join_date"=>"2009-03-05T20:35:40Z"},
  "stats"=>
   {"Puppet"=>{"count"=>1, "star"=>0},
    "Processing"=>{"count"=>1, "star"=>0},
    "Go"=>{"count"=>2, "star"=>1},
    "Ruby"=>{"count"=>2, "star"=>7},
    "JavaScript"=>{"count"=>1, "star"=>0},
    "Clojure"=>{"count"=>3, "star"=>11}}},
 {"profile"=>
   {"username"=>"devinreams",
    "fullname"=>"Devin Reams",
    "location"=>"Portland, ME",
    "email"=>"devin@github.com",
    "link"=>"http://devin.reams.me",
    "join_date"=>"2009-01-27T00:47:34Z"},
  "stats"=>{"CSS"=>{"count"=>3, "star"=>1}, "PHP"=>{"count"=>2, "star"=>0}}},
 {"profile"=>
   {"username"=>"dewski",
    "fullname"=>"Garrett Bjerkhoel",
    "location"=>"Roseville, CA",
    "email"=>"garrett@github.com",
    "link"=>"http://twitter.com/garrettb",
    "join_date"=>"2009-05-01T16:46:23Z"},
  "stats"=>
   {"Ruby"=>{"count"=>17, "star"=>395},
    "JavaScript"=>{"count"=>4, "star"=>181},
    "Go"=>{"count"=>1, "star"=>0},
    "Python"=>{"count"=>2, "star"=>2}}},
 {"profile"=>
   {"username"=>"dgraham",
    "fullname"=>"David Graham",
    "location"=>"Denver, CO, USA",
    "email"=>"dgraham@github.com",
    "link"=>"https://twitter.com/davidgraham",
    "join_date"=>"2009-09-01T21:54:08Z"},
  "stats"=>
   {"JavaScript"=>{"count"=>2, "star"=>19},
    "Rust"=>{"count"=>1, "star"=>1},
    "VimL"=>{"count"=>2, "star"=>1},
    "CSS"=>{"count"=>2, "star"=>2},
    "Ruby"=>{"count"=>4, "star"=>84},
    "C"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"dice",
    "fullname"=>"Daisuke Don Horie",
    "location"=>"Joined on Mar 18, 2011",
    "email"=>"",
    "link"=>"",
    "join_date"=>"2011-03-18T10:07:53Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"dreww",
    "fullname"=>"Drew Woods",
    "location"=>"Portland, OR",
    "email"=>"dreww@github.com",
    "link"=>"https://twitter.com/dreww",
    "join_date"=>"2010-05-11T14:56:51Z"},
  "stats"=>
   {"JavaScript"=>{"count"=>3, "star"=>9},
    "Ruby"=>{"count"=>2, "star"=>6},
    "PHP"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"dsorkin",
    "fullname"=>"Derek Sorkin",
    "location"=>"San Francisco, CA",
    "email"=>"sorkin@github.com",
    "link"=>"Joined on Sep 17, 2012",
    "join_date"=>"2012-09-17T18:31:15Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"ElizabethN",
    "fullname"=>"Elizabeth Naramore",
    "location"=>"Cincinnati, Ohio",
    "email"=>"elizabeth@naramore.net",
    "link"=>"Joined on Feb 24, 2009",
    "join_date"=>"2009-02-24T19:33:15Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"emilyistoofunky",
    "fullname"=>"Emily Gould",
    "location"=>"Dallas, TX",
    "email"=>"Joined on Jun 25, 2013",
    "link"=>"",
    "join_date"=>"2013-06-25T17:27:58Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"erebor",
    "fullname"=>"Ryan Waldron",
    "location"=>"Huntsville, AL",
    "email"=>"erebor@github.com",
    "link"=>"http://erebor.com",
    "join_date"=>"2008-04-04T02:35:08Z"},
  "stats"=>
   {"Ruby"=>{"count"=>3, "star"=>6},
    "Python"=>{"count"=>1, "star"=>4},
    "Objective-C"=>{"count"=>1, "star"=>1},
    "Java"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"fabianperez",
    "fullname"=>"Fabian Perez",
    "location"=>"San Francisco, CA",
    "email"=>"http://deeplyoptional.com",
    "link"=>"Joined on Oct 22, 2009",
    "join_date"=>"2009-10-22T22:49:28Z"},
  "stats"=>
   {"CSS"=>{"count"=>3, "star"=>0},
    "CoffeeScript"=>{"count"=>3, "star"=>0},
    "JavaScript"=>{"count"=>4, "star"=>4}}},
 {"profile"=>
   {"username"=>"Foggybtmgirl",
    "fullname"=>"Heather A. Baldry",
    "location"=>"San Francisco, CA",
    "email"=>"heather@github.com",
    "link"=>"Joined on May 3, 2011",
    "join_date"=>"2011-05-03T21:39:07Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"fooforge",
    "fullname"=>"Mike Adolphs",
    "location"=>"Berlin, Germany",
    "email"=>"mike@github.com",
    "link"=>"http://fooforge.com/",
    "join_date"=>"2011-08-04T19:41:14Z"},
  "stats"=>
   {"CSS"=>{"count"=>1, "star"=>1},
    "Shell"=>{"count"=>5, "star"=>15},
    "Ruby"=>{"count"=>16, "star"=>54},
    "JavaScript"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"gjtorikian",
    "fullname"=>"Garen Torikian",
    "location"=>"San Francisco, CA",
    "email"=>"gjtorikian@gmail.com",
    "link"=>"Joined on Mar 16, 2009",
    "join_date"=>"2009-03-16T20:40:12Z"},
  "stats"=>
   {"Ruby"=>{"count"=>25, "star"=>149},
    "CoffeeScript"=>{"count"=>4, "star"=>119},
    "JavaScript"=>{"count"=>16, "star"=>198},
    "Java"=>{"count"=>2, "star"=>87},
    "Go"=>{"count"=>1, "star"=>0},
    "HTML"=>{"count"=>2, "star"=>369},
    "C"=>{"count"=>2, "star"=>9},
    "CSS"=>{"count"=>7, "star"=>1},
    "Python"=>{"count"=>2, "star"=>17},
    "Shell"=>{"count"=>2, "star"=>1},
    "Perl"=>{"count"=>1, "star"=>1},
    "D"=>{"count"=>1, "star"=>1},
    "C++"=>{"count"=>1, "star"=>8},
    "PHP"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"grantr",
    "fullname"=>"Grant Rodgers",
    "location"=>"Seattle, WA",
    "email"=>"grantr@gmail.com",
    "link"=>"Joined on Feb 23, 2008",
    "join_date"=>"2008-02-23T17:37:28Z"},
  "stats"=>
   {"Ruby"=>{"count"=>22, "star"=>233},
    "CSS"=>{"count"=>1, "star"=>0},
    "Shell"=>{"count"=>1, "star"=>2},
    "VimL"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"gregose",
    "fullname"=>"Greg Ose",
    "location"=>"http://nullmethod.com",
    "email"=>"Joined on Oct 4, 2010",
    "link"=>"",
    "join_date"=>"2010-10-04T23:21:59Z"},
  "stats"=>
   {"C++"=>{"count"=>1, "star"=>1},
    "CSS"=>{"count"=>2, "star"=>0},
    "JavaScript"=>{"count"=>2, "star"=>16},
    "C"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"Haacked",
    "fullname"=>"Phil Haack",
    "location"=>"Bellevue, WA",
    "email"=>"http://haacked.com/",
    "link"=>"Joined on Aug 8, 2008",
    "join_date"=>"2008-08-08T03:36:05Z"},
  "stats"=>
   {"C#"=>{"count"=>24, "star"=>1022},
    "Ruby"=>{"count"=>1, "star"=>7},
    "Shell"=>{"count"=>1, "star"=>1},
    "JavaScript"=>{"count"=>9, "star"=>83},
    "PowerShell"=>{"count"=>1, "star"=>7}}},
 {"profile"=>
   {"username"=>"haleygirl",
    "fullname"=>"Haley Yoder",
    "location"=>"haley.yoder@github.com",
    "email"=>"Joined on Sep 23, 2013",
    "link"=>"",
    "join_date"=>"2013-09-23T17:47:32Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"hoolio",
    "fullname"=>"Julio Avalos",
    "location"=>"San Francisco",
    "email"=>"Joined on Dec 2, 2012",
    "link"=>"",
    "join_date"=>"2012-12-02T19:04:44Z"},
  "stats"=>{"JavaScript"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"house",
    "fullname"=>"Allison House",
    "location"=>"http://allison.house",
    "email"=>"Joined on Jun 16, 2010",
    "link"=>"",
    "join_date"=>"2010-06-16T15:37:19Z"},
  "stats"=>
   {"CSS"=>{"count"=>4, "star"=>69}, "JavaScript"=>{"count"=>1, "star"=>5}}},
 {"profile"=>
   {"username"=>"izuzak",
    "fullname"=>"Ivan Žužak",
    "location"=>"izuzak@gmail.com",
    "email"=>"http://ivanzuzak.info",
    "link"=>"Joined on Dec 7, 2008",
    "join_date"=>"2008-12-07T19:52:51Z"},
  "stats"=>
   {"JavaScript"=>{"count"=>6, "star"=>170},
    "C#"=>{"count"=>1, "star"=>0},
    "CoffeeScript"=>{"count"=>2, "star"=>12},
    "Python"=>{"count"=>5, "star"=>22},
    "CSS"=>{"count"=>1, "star"=>24}}},
 {"profile"=>
   {"username"=>"jakeboxer",
    "fullname"=>"Jake Boxer",
    "location"=>"San Francisco, CA",
    "email"=>"jake@github.com",
    "link"=>"http://jakeboxer.com/",
    "join_date"=>"2009-05-12T05:58:47Z"},
  "stats"=>
   {"C#"=>{"count"=>3, "star"=>1},
    "Ruby"=>{"count"=>8, "star"=>6},
    "Shell"=>{"count"=>1, "star"=>1},
    "Objective-C"=>{"count"=>5, "star"=>341},
    "CSS"=>{"count"=>1, "star"=>50},
    "C"=>{"count"=>1, "star"=>1},
    "JavaScript"=>{"count"=>2, "star"=>1},
    "C++"=>{"count"=>1, "star"=>0},
    "Python"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"jakedouglas",
    "fullname"=>"Jake Douglas",
    "location"=>"Seattle, WA",
    "email"=>"jakecdouglas@gmail.com",
    "link"=>"Joined on Jul 28, 2008",
    "join_date"=>"2008-07-28T00:52:58Z"},
  "stats"=>
   {"C"=>{"count"=>4, "star"=>39},
    "Scala"=>{"count"=>1, "star"=>16},
    "Ruby"=>{"count"=>5, "star"=>58},
    "Java"=>{"count"=>1, "star"=>11},
    "OCaml"=>{"count"=>1, "star"=>6}}},
 {"profile"=>
   {"username"=>"jasoncostello",
    "fullname"=>"Jason Costello",
    "location"=>"San Francisco, CA",
    "email"=>"jason@github.com",
    "link"=>"Joined on Sep 26, 2010",
    "join_date"=>"2010-09-26T19:46:13Z"},
  "stats"=>{"CSS"=>{"count"=>1, "star"=>73}}},
 {"profile"=>
   {"username"=>"jasonlong",
    "fullname"=>"Jason Long",
    "location"=>"Columbus, Ohio",
    "email"=>"jlong@github.com",
    "link"=>"http://twitter.com/jasonlong",
    "join_date"=>"2008-04-09T20:39:25Z"},
  "stats"=>
   {"VimL"=>{"count"=>2, "star"=>292},
    "Ruby"=>{"count"=>3, "star"=>624},
    "HTML"=>{"count"=>1, "star"=>0},
    "CSS"=>{"count"=>6, "star"=>551},
    "JavaScript"=>{"count"=>6, "star"=>81},
    "PHP"=>{"count"=>2, "star"=>23}}},
 {"profile"=>
   {"username"=>"jasonrudolph",
    "fullname"=>"Jason Rudolph",
    "location"=>"North Carolina, USA",
    "email"=>"http://jasonrudolph.com",
    "link"=>"Joined on Mar 13, 2008",
    "join_date"=>"2008-03-13T15:02:53Z"},
  "stats"=>
   {"HTML"=>{"count"=>1, "star"=>24},
    "Ruby"=>{"count"=>3, "star"=>98},
    "Shell"=>{"count"=>1, "star"=>376},
    "Python"=>{"count"=>1, "star"=>1},
    "Clojure"=>{"count"=>1, "star"=>39},
    "Groovy"=>{"count"=>3, "star"=>45},
    "JavaScript"=>{"count"=>1, "star"=>5}}},
 {"profile"=>
   {"username"=>"jaw6",
    "fullname"=>"Joshua Wehner",
    "location"=>"Minneapolis, MN",
    "email"=>"joshua.wehner@github.com",
    "link"=>"http://joshuawehner.com/",
    "join_date"=>"2008-03-03T20:46:58Z"},
  "stats"=>
   {"Ruby"=>{"count"=>11, "star"=>21},
    "JavaScript"=>{"count"=>1, "star"=>2},
    "Objective-J"=>{"count"=>1, "star"=>5}}},
 {"profile"=>
   {"username"=>"jbarnette",
    "fullname"=>"John Barnette",
    "location"=>"New Orleans",
    "email"=>"jbarnette@github.com",
    "link"=>"http://jbarnette.com",
    "join_date"=>"2008-03-14T19:14:15Z"},
  "stats"=>
   {"Ruby"=>{"count"=>40, "star"=>1320},
    "Rust"=>{"count"=>1, "star"=>0},
    "CoffeeScript"=>{"count"=>1, "star"=>1},
    "C#"=>{"count"=>1, "star"=>2},
    "JavaScript"=>{"count"=>2, "star"=>6}}},
 {"profile"=>
   {"username"=>"jch",
    "fullname"=>"Jerry Cheung",
    "location"=>"Berkeley, CA",
    "email"=>"jollyjerry@gmail.com",
    "link"=>"http://jch.github.io",
    "join_date"=>"2008-08-07T10:05:25Z"},
  "stats"=>
   {"Ruby"=>{"count"=>29, "star"=>135},
    "Shell"=>{"count"=>1, "star"=>3},
    "CSS"=>{"count"=>2, "star"=>1},
    "CoffeeScript"=>{"count"=>1, "star"=>4},
    "JavaScript"=>{"count"=>5, "star"=>13},
    "Perl"=>{"count"=>1, "star"=>3},
    "Objective-C"=>{"count"=>3, "star"=>15}}},
 {"profile"=>
   {"username"=>"jdennes",
    "fullname"=>"James Dennes",
    "location"=>"Berlin, Germany",
    "email"=>"http://jdenn.es",
    "link"=>"Joined on Mar 19, 2009",
    "join_date"=>"2009-03-19T22:11:12Z"},
  "stats"=>
   {"Ruby"=>{"count"=>11, "star"=>21},
    "CSS"=>{"count"=>3, "star"=>5},
    "Perl"=>{"count"=>1, "star"=>0},
    "C#"=>{"count"=>1, "star"=>1},
    "Java"=>{"count"=>1, "star"=>3},
    "JavaScript"=>{"count"=>2, "star"=>8},
    "Python"=>{"count"=>8, "star"=>17}}},
 {"profile"=>
   {"username"=>"jdmaturen",
    "fullname"=>"JD Maturen",
    "location"=>"http://twitter.com/jdmaturen",
    "email"=>"Joined on Apr 5, 2009",
    "link"=>"",
    "join_date"=>"2009-04-05T21:04:53Z"},
  "stats"=>
   {"Python"=>{"count"=>1, "star"=>15}, "Java"=>{"count"=>2, "star"=>11}}},
 {"profile"=>
   {"username"=>"jdpace",
    "fullname"=>"Jared Pace",
    "location"=>"Portland, OR",
    "email"=>"jdpace@github.com",
    "link"=>"Joined on Mar 7, 2008",
    "join_date"=>"2008-03-07T16:45:55Z"},
  "stats"=>
   {"Shell"=>{"count"=>2, "star"=>4},
    "Ruby"=>{"count"=>12, "star"=>94},
    "JavaScript"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"jeejkang",
    "fullname"=>"James Kang",
    "location"=>"San Francisco",
    "email"=>"kang@github.com",
    "link"=>"http://jeejkang.com",
    "join_date"=>"2012-07-27T20:03:24Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"jessephus",
    "fullname"=>"Jesse Geraci",
    "location"=>"San Francisco",
    "email"=>"Joined on Dec 8, 2013",
    "link"=>"",
    "join_date"=>"2013-12-08T02:54:39Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"jesseplusplus",
    "fullname"=>"Jesse Toth",
    "location"=>"San Francisco, CA",
    "email"=>"Joined on Aug 31, 2010",
    "link"=>"",
    "join_date"=>"2010-08-31T23:29:18Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"jessla",
    "fullname"=>"Jess Allen",
    "location"=>"San Francisco",
    "email"=>"jess@github.com",
    "link"=>"Joined on Jan 9, 2013",
    "join_date"=>"2013-01-09T18:21:37Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"jglovier",
    "fullname"=>"Joel Glovier",
    "location"=>"Mechanicsburg, PA",
    "email"=>"jglovier@github.com",
    "link"=>"http://joelglovier.com",
    "join_date"=>"2012-01-10T21:52:01Z"},
  "stats"=>
   {"HTML"=>{"count"=>2, "star"=>17},
    "CSS"=>{"count"=>3, "star"=>85},
    "JavaScript"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"jgreet",
    "fullname"=>"John Greet",
    "location"=>"San Francisco, CA",
    "email"=>"jgreet@github.com",
    "link"=>"Joined on Sep 7, 2010",
    "join_date"=>"2010-09-07T23:58:27Z"},
  "stats"=>{"JavaScript"=>{"count"=>1, "star"=>3}}},
 {"profile"=>
   {"username"=>"jhosman",
    "fullname"=>"Jess Hosman",
    "location"=>"Joined on Nov 9, 2011",
    "email"=>"",
    "link"=>"",
    "join_date"=>"2011-11-09T16:19:59Z"},
  "stats"=>
   {"Python"=>{"count"=>2, "star"=>2}, "C++"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"jlord",
    "fullname"=>"Jessica Lord",
    "location"=>"Portland, Ore",
    "email"=>"https://jlord.github.io",
    "link"=>"Joined on Jan 5, 2012",
    "join_date"=>"2012-01-05T03:24:52Z"},
  "stats"=>
   {"HTML"=>{"count"=>3, "star"=>798},
    "JavaScript"=>{"count"=>40, "star"=>684},
    "CSS"=>{"count"=>10, "star"=>47},
    "PHP"=>{"count"=>3, "star"=>3},
    "Shell"=>{"count"=>1, "star"=>5}}},
 {"profile"=>
   {"username"=>"jnewland",
    "fullname"=>"Jesse Newland",
    "location"=>"San Francisco, CA",
    "email"=>"jesse@github.com",
    "link"=>"http://twitter.com/jnewland",
    "join_date"=>"2008-01-25T02:28:12Z"},
  "stats"=>
   {"PHP"=>{"count"=>1, "star"=>0},
    "Shell"=>{"count"=>1, "star"=>16},
    "Ruby"=>{"count"=>34, "star"=>532},
    "Python"=>{"count"=>1, "star"=>7},
    "JavaScript"=>{"count"=>3, "star"=>55}}},
 {"profile"=>
   {"username"=>"jnunemaker",
    "fullname"=>"John Nunemaker",
    "location"=>"South Bend, IN, USA",
    "email"=>"john@github.com",
    "link"=>"http://johnnunemaker.com",
    "join_date"=>"2008-02-13T18:00:42Z"},
  "stats"=>
   {"Ruby"=>{"count"=>46, "star"=>2960},
    "JavaScript"=>{"count"=>3, "star"=>587},
    "Clojure"=>{"count"=>1, "star"=>0},
    "Shell"=>{"count"=>1, "star"=>12},
    "PHP"=>{"count"=>1, "star"=>9},
    "Python"=>{"count"=>1, "star"=>4}}},
 {"profile"=>
   {"username"=>"joewilliams",
    "fullname"=>"Joe Williams",
    "location"=>"Seattle, WA",
    "email"=>"williams.joe@gmail.com",
    "link"=>"https://twitter.com/williamsjoe",
    "join_date"=>"2009-01-05T22:44:13Z"},
  "stats"=>
   {"Ruby"=>{"count"=>11, "star"=>265},
    "CSS"=>{"count"=>1, "star"=>2},
    "Shell"=>{"count"=>2, "star"=>12},
    "C"=>{"count"=>4, "star"=>45},
    "Perl"=>{"count"=>1, "star"=>16},
    "Erlang"=>{"count"=>6, "star"=>119}}},
 {"profile"=>
   {"username"=>"JohnCreek",
    "fullname"=>"Joao Ribeiro",
    "location"=>"San Francisco, CA",
    "email"=>"joao.ribeiro@github.com",
    "link"=>"http://wodzgn.blogspot.com",
    "join_date"=>"2013-04-22T17:12:31Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"johndbritton",
    "fullname"=>"John Britton",
    "location"=>"New York",
    "email"=>"public@johndbritton.com",
    "link"=>"http://www.johndbritton.com",
    "join_date"=>"2009-09-04T18:06:13Z"},
  "stats"=>
   {"Python"=>{"count"=>2, "star"=>1},
    "Ruby"=>{"count"=>10, "star"=>44},
    "Shell"=>{"count"=>1, "star"=>6},
    "CSS"=>{"count"=>1, "star"=>2},
    "JavaScript"=>{"count"=>6, "star"=>25},
    "PHP"=>{"count"=>3, "star"=>8},
    "Objective-C"=>{"count"=>2, "star"=>2}}},
 {"profile"=>
   {"username"=>"johnyerhot",
    "fullname"=>"John Yerhot",
    "location"=>"Roseville, CA",
    "email"=>"john.yerhot@github.com",
    "link"=>"http://john.yerhot.org",
    "join_date"=>"2008-08-14T18:36:54Z"},
  "stats"=>{"Ruby"=>{"count"=>13, "star"=>42}, "C"=>{"count"=>1, "star"=>3}}},
 {"profile"=>
   {"username"=>"jonmagic",
    "fullname"=>"Jonathan Hoyt",
    "location"=>"San Mateo California",
    "email"=>"hoyt@github.com",
    "link"=>"http://theprogrammingbutler.com",
    "join_date"=>"2008-02-22T17:26:44Z"},
  "stats"=>
   {"JavaScript"=>{"count"=>9, "star"=>125},
    "Ruby"=>{"count"=>28, "star"=>212},
    "CoffeeScript"=>{"count"=>2, "star"=>2},
    "C++"=>{"count"=>2, "star"=>1},
    "Go"=>{"count"=>1, "star"=>3},
    "Python"=>{"count"=>2, "star"=>3}}},
 {"profile"=>
   {"username"=>"jonrohan",
    "fullname"=>"Jon Rohan",
    "location"=>"Atlanta, GA",
    "email"=>"http://twitter.com/jonrohan",
    "link"=>"Joined on Feb 12, 2009",
    "join_date"=>"2009-02-12T18:22:32Z"},
  "stats"=>
   {"CSS"=>{"count"=>4, "star"=>9},
    "CoffeeScript"=>{"count"=>3, "star"=>4},
    "C"=>{"count"=>5, "star"=>7},
    "Java"=>{"count"=>1, "star"=>0},
    "Objective-C"=>{"count"=>1, "star"=>0},
    "JavaScript"=>{"count"=>4, "star"=>4}}},
 {"profile"=>
   {"username"=>"jordanmccullough",
    "fullname"=>"Jordan McCullough",
    "location"=>"Denver, Colorado",
    "email"=>"jordan@github.com",
    "link"=>"http://github.com/jordanmccullough",
    "join_date"=>"2010-08-02T20:26:32Z"},
  "stats"=>
   {"CSS"=>{"count"=>2, "star"=>5},
    "JavaScript"=>{"count"=>5, "star"=>57},
    "Ruby"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"josh",
    "fullname"=>"Joshua Peek",
    "location"=>"San Francisco, CA",
    "email"=>"josh@joshpeek.com",
    "link"=>"https://twitter.com/joshpeek",
    "join_date"=>"2008-02-03T22:05:54Z"},
  "stats"=>
   {"Ruby"=>{"count"=>16, "star"=>1540},
    "Shell"=>{"count"=>7, "star"=>178},
    "C"=>{"count"=>2, "star"=>11},
    "CoffeeScript"=>{"count"=>3, "star"=>450},
    "JavaScript"=>{"count"=>13, "star"=>1594},
    "Go"=>{"count"=>2, "star"=>26}}},
 {"profile"=>
   {"username"=>"joshaber",
    "fullname"=>"Josh Abernathy",
    "location"=>"The Gem City",
    "email"=>"josh@github.com",
    "link"=>"http://twitter.com/joshaber",
    "join_date"=>"2008-06-15T00:25:05Z"},
  "stats"=>
   {"Swift"=>{"count"=>1, "star"=>313},
    "C"=>{"count"=>2, "star"=>313},
    "CSS"=>{"count"=>1, "star"=>0},
    "Objective-C"=>{"count"=>24, "star"=>881},
    "Clojure"=>{"count"=>1, "star"=>290},
    "Ruby"=>{"count"=>1, "star"=>4}}},
 {"profile"=>
   {"username"=>"joshvera",
    "fullname"=>"Josh Vera",
    "location"=>"New York, NY",
    "email"=>"vera@github.com",
    "link"=>"Joined on Sep 12, 2008",
    "join_date"=>"2008-09-12T01:45:49Z"},
  "stats"=>
   {"VimL"=>{"count"=>1, "star"=>1},
    "Haskell"=>{"count"=>1, "star"=>2},
    "Shell"=>{"count"=>1, "star"=>11},
    "Objective-C"=>{"count"=>1, "star"=>57}}},
 {"profile"=>
   {"username"=>"jrday",
    "fullname"=>"Ryan Day",
    "location"=>"San Francisco",
    "email"=>"Joined on May 8, 2011",
    "link"=>"",
    "join_date"=>"2011-05-08T03:19:15Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"jroll",
    "fullname"=>"Jessica Roll",
    "location"=>"San Francisco, CA",
    "email"=>"jessica@github.com",
    "link"=>"Joined on Feb 4, 2013",
    "join_date"=>"2013-02-04T19:48:24Z"},
  "stats"=>{"CSS"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"jspahrsummers",
    "fullname"=>"Justin Spahr-Summers",
    "location"=>"San Francisco, CA",
    "email"=>"justin@jspahrsummers.com",
    "link"=>"http://jspahrsummers.com",
    "join_date"=>"2010-10-08T15:39:49Z"},
  "stats"=>
   {"D"=>{"count"=>1, "star"=>0},
    "VimL"=>{"count"=>2, "star"=>10},
    "Haskell"=>{"count"=>5, "star"=>123},
    "Swift"=>{"count"=>5, "star"=>872},
    "Shell"=>{"count"=>4, "star"=>237},
    "Objective-C"=>{"count"=>9, "star"=>581},
    "C++"=>{"count"=>1, "star"=>29},
    "C"=>{"count"=>1, "star"=>19},
    "Ruby"=>{"count"=>1, "star"=>2},
    "Lua"=>{"count"=>1, "star"=>6},
    "Clojure"=>{"count"=>1, "star"=>28}}},
 {"profile"=>
   {"username"=>"jssjr",
    "fullname"=>"Scott Sanders",
    "location"=>"Charleston, SC",
    "email"=>"scott@jssjr.com",
    "link"=>"http://www.jssjr.com",
    "join_date"=>"2009-04-30T15:26:38Z"},
  "stats"=>
   {"Ruby"=>{"count"=>8, "star"=>110},
    "Python"=>{"count"=>4, "star"=>342},
    "C"=>{"count"=>1, "star"=>44}}},
 {"profile"=>
   {"username"=>"juliamae",
    "fullname"=>"Julia West",
    "location"=>"San Francisco, CA",
    "email"=>"julia@github.com",
    "link"=>"http://juliawe.st",
    "join_date"=>"2008-02-25T17:25:55Z"},
  "stats"=>
   {"Ruby"=>{"count"=>5, "star"=>20},
    "Shell"=>{"count"=>1, "star"=>11},
    "Objective-C"=>{"count"=>1, "star"=>2},
    "JavaScript"=>{"count"=>2, "star"=>20}}},
 {"profile"=>
   {"username"=>"karthik",
    "fullname"=>"Karthik Ram",
    "location"=>"Berkeley, CA",
    "email"=>"k@karthik.io",
    "link"=>"http://inundata.org",
    "join_date"=>"2009-10-12T04:41:48Z"},
  "stats"=>
   {"R"=>{"count"=>14, "star"=>299},
    "CSS"=>{"count"=>6, "star"=>12},
    "Shell"=>{"count"=>2, "star"=>64},
    "TeX"=>{"count"=>6, "star"=>184},
    "Perl"=>{"count"=>1, "star"=>1},
    "JavaScript"=>{"count"=>2, "star"=>5},
    "Python"=>{"count"=>4, "star"=>32}}},
 {"profile"=>
   {"username"=>"kasima",
    "fullname"=>"Kasima Tharnpipitchai",
    "location"=>"San Francisco, CA",
    "email"=>"http://2ndrategeniuses.com",
    "link"=>"Joined on Oct 29, 2009",
    "join_date"=>"2009-10-29T16:54:44Z"},
  "stats"=>
   {"CSS"=>{"count"=>2, "star"=>8},
    "Shell"=>{"count"=>1, "star"=>1},
    "Python"=>{"count"=>1, "star"=>0},
    "JavaScript"=>{"count"=>5, "star"=>9},
    "CoffeeScript"=>{"count"=>2, "star"=>0},
    "Ruby"=>{"count"=>3, "star"=>4},
    "PHP"=>{"count"=>1, "star"=>3}}},
 {"profile"=>
   {"username"=>"kateguarente",
    "fullname"=>"Kate Guarente",
    "location"=>"San Francisco",
    "email"=>"kate@github.com",
    "link"=>"Joined on Sep 26, 2012",
    "join_date"=>"2012-09-26T20:47:30Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"kcshearon",
    "fullname"=>"Kelly Shearon",
    "location"=>"San Francisco, CA",
    "email"=>"kelly.shearon@github.com",
    "link"=>"Joined on May 6, 2013",
    "join_date"=>"2013-05-06T17:12:54Z"},
  "stats"=>
   {"CoffeeScript"=>{"count"=>1, "star"=>0}, "CSS"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"kdaigle",
    "fullname"=>"Kyle Daigle",
    "location"=>"Vernon, CT",
    "email"=>"kyle.daigle@github.com",
    "link"=>"http://www.kyledaigle.com",
    "join_date"=>"2008-03-07T14:32:21Z"},
  "stats"=>
   {"Ruby"=>{"count"=>9, "star"=>19},
    "CSS"=>{"count"=>2, "star"=>1},
    "Go"=>{"count"=>1, "star"=>2},
    "Shell"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"keavy",
    "fullname"=>"Keavy McMinn",
    "location"=>"Boulder, CO",
    "email"=>"keavy@github.com",
    "link"=>"http://www.keavy.co.uk",
    "join_date"=>"2008-04-11T08:06:38Z"},
  "stats"=>
   {"Ruby"=>{"count"=>7, "star"=>22}, "JavaScript"=>{"count"=>1, "star"=>3}}},
 {"profile"=>
   {"username"=>"keithduncan",
    "fullname"=>"Keith Duncan",
    "location"=>"Brighton",
    "email"=>"keith.duncan@github.com",
    "link"=>"Joined on Aug 26, 2008",
    "join_date"=>"2008-08-26T21:05:54Z"},
  "stats"=>
   {"Objective-C++"=>{"count"=>1, "star"=>0},
    "C"=>{"count"=>5, "star"=>0},
    "Objective-C"=>{"count"=>4, "star"=>17}}},
 {"profile"=>
   {"username"=>"kelseyschimm",
    "fullname"=>"Kelsey Schimmelman",
    "location"=>"kelsey.schimmelman@github.com",
    "email"=>"Joined on Apr 14, 2013",
    "link"=>"",
    "join_date"=>"2013-04-14T19:45:12Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"kevinsawicki",
    "fullname"=>"Kevin Sawicki",
    "location"=>"Redwood City, CA",
    "email"=>"kevin@github.com",
    "link"=>"https://twitter.com/kevinsawicki",
    "join_date"=>"2011-03-15T16:46:18Z"},
  "stats"=>
   {"CoffeeScript"=>{"count"=>10, "star"=>28},
    "CSS"=>{"count"=>3, "star"=>81},
    "Java"=>{"count"=>24, "star"=>637},
    "JavaScript"=>{"count"=>6, "star"=>29},
    "Shell"=>{"count"=>2, "star"=>2},
    "C"=>{"count"=>1, "star"=>2},
    "Ruby"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"leehuffman",
    "fullname"=>"Lee Huffman",
    "location"=>"Bellingham, WA",
    "email"=>"huffman@github.com",
    "link"=>"https://twitter.com/leehuffman",
    "join_date"=>"2010-09-17T19:22:38Z"},
  "stats"=>{"Ruby"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"leereilly",
    "fullname"=>"Lee Reilly",
    "location"=>"San Francisco, CA",
    "email"=>"lee@github.com",
    "link"=>"http://leereilly.net",
    "join_date"=>"2009-08-31T05:28:49Z"},
  "stats"=>
   {"Ruby"=>{"count"=>19, "star"=>439},
    "CSS"=>{"count"=>2, "star"=>3},
    "JavaScript"=>{"count"=>4, "star"=>16},
    "Dart"=>{"count"=>1, "star"=>0},
    "PHP"=>{"count"=>1, "star"=>1},
    "Clojure"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"lildude",
    "fullname"=>"Colin Seymour",
    "location"=>"United Kingdom",
    "email"=>"http://lildude.co.uk",
    "link"=>"Joined on Feb 19, 2011",
    "join_date"=>"2011-02-19T17:40:07Z"},
  "stats"=>
   {"Ruby"=>{"count"=>4, "star"=>1},
    "PHP"=>{"count"=>13, "star"=>39},
    "CSS"=>{"count"=>1, "star"=>0},
    "CoffeeScript"=>{"count"=>1, "star"=>0},
    "VimL"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"lizclink",
    "fullname"=>"Liz Clinkenbeard",
    "location"=>"San Francisco",
    "email"=>"Joined on Oct 15, 2012",
    "link"=>"",
    "join_date"=>"2012-10-15T17:47:08Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"lukehefson",
    "fullname"=>"Luke Hefson",
    "location"=>"Brighton, UK",
    "email"=>"luke@github.com",
    "link"=>"http://heavygradient.com",
    "join_date"=>"2012-02-24T13:54:44Z"},
  "stats"=>
   {"Objective-C"=>{"count"=>1, "star"=>0},
    "JavaScript"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"lynnwallenstein",
    "fullname"=>"Lynn Wallenstein",
    "location"=>"San Francisco, CA",
    "email"=>"lynn@github.com",
    "link"=>"http://www.lynn.io",
    "join_date"=>"2008-03-09T00:06:28Z"},
  "stats"=>
   {"CSS"=>{"count"=>5, "star"=>4},
    "JavaScript"=>{"count"=>5, "star"=>48},
    "CoffeeScript"=>{"count"=>1, "star"=>0},
    "PHP"=>{"count"=>1, "star"=>3}}},
 {"profile"=>
   {"username"=>"maddox",
    "fullname"=>"Jon Maddox",
    "location"=>"Richmond, Va",
    "email"=>"jon@jonmaddox.com",
    "link"=>"http://jonmaddox.com",
    "join_date"=>"2008-02-13T23:33:31Z"},
  "stats"=>
   {"Ruby"=>{"count"=>22, "star"=>382},
    "CoffeeScript"=>{"count"=>1, "star"=>13},
    "Objective-C"=>{"count"=>10, "star"=>51},
    "Shell"=>{"count"=>1, "star"=>507},
    "JavaScript"=>{"count"=>6, "star"=>43},
    "C"=>{"count"=>2, "star"=>5},
    "Python"=>{"count"=>2, "star"=>3}}},
 {"profile"=>
   {"username"=>"mastahyeti",
    "fullname"=>"Ben Toews",
    "location"=>"Chicago, IL",
    "email"=>"http://btoe.ws",
    "link"=>"Joined on Oct 21, 2011",
    "join_date"=>"2011-10-21T22:26:39Z"},
  "stats"=>
   {"JavaScript"=>{"count"=>1, "star"=>45},
    "Ruby"=>{"count"=>2, "star"=>8},
    "Python"=>{"count"=>9, "star"=>41}}},
 {"profile"=>
   {"username"=>"matthewmccullough",
    "fullname"=>"Matthew McCullough",
    "location"=>"Denver, CO USA",
    "email"=>"matthew@github.com",
    "link"=>"http://ambientideas.com/blog",
    "join_date"=>"2008-09-15T20:54:43Z"},
  "stats"=>
   {"Java"=>{"count"=>11, "star"=>48},
    "CSS"=>{"count"=>1, "star"=>2},
    "Shell"=>{"count"=>5, "star"=>315},
    "Groovy"=>{"count"=>1, "star"=>0},
    "Ruby"=>{"count"=>1, "star"=>0},
    "Objective-C"=>{"count"=>1, "star"=>4},
    "Python"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"mattyoho",
    "fullname"=>"Matt Yoho",
    "location"=>"San Francisco, CA, USA",
    "email"=>"yoho@github.com",
    "link"=>"http://mattyoho.com/",
    "join_date"=>"2008-07-19T19:29:53Z"},
  "stats"=>
   {"CSS"=>{"count"=>1, "star"=>0},
    "Clojure"=>{"count"=>1, "star"=>1},
    "Ruby"=>{"count"=>6, "star"=>75},
    "Scheme"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"mcolyer",
    "fullname"=>"Matt Colyer",
    "location"=>"Redwood City, CA",
    "email"=>"http://matt.colyer.name",
    "link"=>"Joined on Feb 28, 2008",
    "join_date"=>"2008-02-28T04:04:51Z"},
  "stats"=>
   {"Ruby"=>{"count"=>13, "star"=>102},
    "Shell"=>{"count"=>1, "star"=>0},
    "JavaScript"=>{"count"=>4, "star"=>6},
    "CoffeeScript"=>{"count"=>1, "star"=>2},
    "Python"=>{"count"=>7, "star"=>6},
    "Assembly"=>{"count"=>1, "star"=>0},
    "Perl"=>{"count"=>1, "star"=>0},
    "C"=>{"count"=>2, "star"=>76},
    "Java"=>{"count"=>1, "star"=>4}}},
 {"profile"=>
   {"username"=>"mdiep",
    "fullname"=>"Matt Diephouse",
    "location"=>"matt@diephouse.com",
    "email"=>"http://matt.diephouse.com",
    "link"=>"Joined on Feb 27, 2008",
    "join_date"=>"2008-02-27T23:31:47Z"},
  "stats"=>
   {"Objective-C"=>{"count"=>7, "star"=>660},
    "Python"=>{"count"=>5, "star"=>61},
    "VimL"=>{"count"=>1, "star"=>0},
    "Ruby"=>{"count"=>1, "star"=>3}}},
 {"profile"=>
   {"username"=>"mdo",
    "fullname"=>"Mark Otto",
    "location"=>"San Francisco, CA",
    "email"=>"https://www.gittip.com/mdo/",
    "link"=>"Joined on Jun 25, 2009",
    "join_date"=>"2009-06-25T02:06:14Z"},
  "stats"=>
   {"CSS"=>{"count"=>17, "star"=>1494},
    "Shell"=>{"count"=>1, "star"=>135},
    "JavaScript"=>{"count"=>2, "star"=>15},
    "Scala"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"meatcoder",
    "fullname"=>"Sim Domingo",
    "location"=>"Philippines",
    "email"=>"sim@github.com",
    "link"=>"Joined on Apr 10, 2008",
    "join_date"=>"2008-04-10T19:32:02Z"},
  "stats"=>
   {"Ruby"=>{"count"=>1, "star"=>1},
    "Objective-C"=>{"count"=>1, "star"=>1},
    "JavaScript"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"mhagger",
    "fullname"=>"Michael Haggerty",
    "location"=>"Berlin, Germany",
    "email"=>"mhagger@alum.mit.edu",
    "link"=>"http://softwareswirl.blogspot.com",
    "join_date"=>"2009-08-26T13:01:43Z"},
  "stats"=>
   {"C"=>{"count"=>1, "star"=>4}, "Python"=>{"count"=>6, "star"=>106}}},
 {"profile"=>
   {"username"=>"mhp",
    "fullname"=>"Michael Procter",
    "location"=>"UK",
    "email"=>"Joined on Apr 8, 2008",
    "link"=>"",
    "join_date"=>"2008-04-08T21:15:51Z"},
  "stats"=>
   {"PHP"=>{"count"=>1, "star"=>0},
    "Python"=>{"count"=>3, "star"=>1},
    "Arduino"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"michaeltwofish",
    "fullname"=>"Michael C. Harris",
    "location"=>"Melbourne, Australia",
    "email"=>"http://twofishcreative.com/michael/blog",
    "link"=>"Joined on Jan 20, 2010",
    "join_date"=>"2010-01-20T03:14:59Z"},
  "stats"=>
   {"PHP"=>{"count"=>11, "star"=>18},
    "Ruby"=>{"count"=>1, "star"=>0},
    "Python"=>{"count"=>1, "star"=>2},
    "JavaScript"=>{"count"=>2, "star"=>2},
    "Puppet"=>{"count"=>2, "star"=>1}}},
 {"profile"=>
   {"username"=>"mikemcquaid",
    "fullname"=>"Mike McQuaid",
    "location"=>"Edinburgh, Scotland",
    "email"=>"mike@mikemcquaid.com",
    "link"=>"http://mikemcquaid.com",
    "join_date"=>"2009-09-09T18:00:06Z"},
  "stats"=>
   {"Ruby"=>{"count"=>5, "star"=>17},
    "HTML"=>{"count"=>1, "star"=>1},
    "Shell"=>{"count"=>3, "star"=>35},
    "C++"=>{"count"=>2, "star"=>24},
    "CoffeeScript"=>{"count"=>1, "star"=>3},
    "PHP"=>{"count"=>1, "star"=>2},
    "Objective-C"=>{"count"=>1, "star"=>0},
    "Java"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"mislav",
    "fullname"=>"Mislav Marohnić",
    "location"=>"Europe",
    "email"=>"mislav.marohnic@gmail.com",
    "link"=>"http://mislav.uniqpath.com",
    "join_date"=>"2008-02-25T20:18:33Z"},
  "stats"=>
   {"HTML"=>{"count"=>1, "star"=>11},
    "Shell"=>{"count"=>4, "star"=>463},
    "Ruby"=>{"count"=>52, "star"=>1981},
    "JavaScript"=>{"count"=>9, "star"=>656},
    "CSS"=>{"count"=>1, "star"=>245},
    "VimL"=>{"count"=>1, "star"=>242},
    "CoffeeScript"=>{"count"=>2, "star"=>11},
    "C"=>{"count"=>1, "star"=>13},
    "PHP"=>{"count"=>1, "star"=>5}}},
 {"profile"=>
   {"username"=>"mtodd",
    "fullname"=>"Matt Todd",
    "location"=>"San Francisco, CA",
    "email"=>"matt@github.com",
    "link"=>"http://maraby.org/",
    "join_date"=>"2008-02-11T06:28:43Z"},
  "stats"=>
   {"C"=>{"count"=>2, "star"=>158},
    "Ruby"=>{"count"=>40, "star"=>223},
    "JavaScript"=>{"count"=>7, "star"=>13},
    "Shell"=>{"count"=>1, "star"=>5},
    "Perl"=>{"count"=>1, "star"=>9},
    "PHP"=>{"count"=>2, "star"=>3},
    "Erlang"=>{"count"=>1, "star"=>2},
    "Java"=>{"count"=>1, "star"=>8}}},
 {"profile"=>
   {"username"=>"muan",
    "fullname"=>"Mu-An",
    "location"=>"Taipei, Taiwan",
    "email"=>"http://muan.co/",
    "link"=>"Joined on Oct 26, 2011",
    "join_date"=>"2011-10-26T12:53:14Z"},
  "stats"=>
   {"HTML"=>{"count"=>1, "star"=>4},
    "CSS"=>{"count"=>9, "star"=>1499},
    "JavaScript"=>{"count"=>12, "star"=>536},
    "CoffeeScript"=>{"count"=>1, "star"=>7},
    "Ruby"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"mutle",
    "fullname"=>"Mutwin Kraus",
    "location"=>"Düsseldorf, Germany",
    "email"=>"http://mutwinkraus.com",
    "link"=>"Joined on Feb 25, 2008",
    "join_date"=>"2008-02-25T17:00:02Z"},
  "stats"=>
   {"Ruby"=>{"count"=>14, "star"=>89},
    "Python"=>{"count"=>1, "star"=>1},
    "VimL"=>{"count"=>1, "star"=>2},
    "JavaScript"=>{"count"=>4, "star"=>164},
    "C"=>{"count"=>1, "star"=>15}}},
 {"profile"=>
   {"username"=>"nakajima",
    "fullname"=>"Pat Nakajima",
    "location"=>"San Francisco",
    "email"=>"patnakajima@gmail.com",
    "link"=>"http://patnakajima.com",
    "join_date"=>"2008-02-20T08:35:46Z"},
  "stats"=>
   {"Ruby"=>{"count"=>69, "star"=>1176},
    "CoffeeScript"=>{"count"=>3, "star"=>5},
    "JavaScript"=>{"count"=>17, "star"=>901}}},
 {"profile"=>
   {"username"=>"nathansobo",
    "fullname"=>"Nathan Sobo",
    "location"=>"Boulder, CO",
    "email"=>"nathan@github.com",
    "link"=>"Joined on Feb 29, 2008",
    "join_date"=>"2008-02-29T18:26:45Z"},
  "stats"=>
   {"CoffeeScript"=>{"count"=>5, "star"=>36},
    "Ruby"=>{"count"=>15, "star"=>824},
    "Objective-C"=>{"count"=>1, "star"=>0},
    "VimL"=>{"count"=>1, "star"=>2},
    "JavaScript"=>{"count"=>4, "star"=>207}}},
 {"profile"=>
   {"username"=>"newmerator",
    "fullname"=>"David Newman",
    "location"=>"San Francisco, CA",
    "email"=>"david@github.com",
    "link"=>"Joined on Feb 21, 2012",
    "join_date"=>"2012-02-21T17:35:09Z"},
  "stats"=>{"CSS"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"nickh",
    "fullname"=>"Nick Hengeveld",
    "location"=>"San Francisco, CA",
    "email"=>"nickh@hengeveld.com",
    "link"=>"Joined on Apr 10, 2008",
    "join_date"=>"2008-04-10T18:59:03Z"},
  "stats"=>
   {"Ruby"=>{"count"=>14, "star"=>28},
    "CSS"=>{"count"=>1, "star"=>2},
    "Shell"=>{"count"=>2, "star"=>1},
    "C#"=>{"count"=>1, "star"=>0},
    "Perl"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"niik",
    "fullname"=>"Markus Olsson",
    "location"=>"Sweden",
    "email"=>"https://twitter.com/niik",
    "link"=>"Joined on Feb 23, 2011",
    "join_date"=>"2011-02-23T14:39:58Z"},
  "stats"=>{"C#"=>{"count"=>8, "star"=>93}}},
 {"profile"=>
   {"username"=>"nuclearsandwich",
    "fullname"=>"Steven! Ragnarök",
    "location"=>"Santa Clara Valley, California",
    "email"=>"steven@nuclearsandwich.com",
    "link"=>"http://nuclearsandwich.com",
    "join_date"=>"2010-08-09T17:31:03Z"},
  "stats"=>
   {"Ruby"=>{"count"=>20, "star"=>26},
    "CSS"=>{"count"=>3, "star"=>2},
    "VimL"=>{"count"=>2, "star"=>6},
    "Shell"=>{"count"=>6, "star"=>7},
    "JavaScript"=>{"count"=>3, "star"=>2},
    "Lua"=>{"count"=>6, "star"=>1},
    "C"=>{"count"=>6, "star"=>5},
    "Python"=>{"count"=>1, "star"=>1},
    "Java"=>{"count"=>4, "star"=>7},
    "CoffeeScript"=>{"count"=>2, "star"=>2},
    "Go"=>{"count"=>1, "star"=>0},
    "Pascal"=>{"count"=>1, "star"=>0},
    "Clojure"=>{"count"=>2, "star"=>3},
    "Fancy"=>{"count"=>3, "star"=>7}}},
 {"profile"=>
   {"username"=>"orderedlist",
    "fullname"=>"Steve Smith",
    "location"=>"South Bend, IN, USA",
    "email"=>"steve@github.com",
    "link"=>"http://orderedlist.com",
    "join_date"=>"2008-02-29T01:15:34Z"},
  "stats"=>
   {"CSS"=>{"count"=>5, "star"=>1119},
    "Ruby"=>{"count"=>3, "star"=>18},
    "JavaScript"=>{"count"=>1, "star"=>10}}},
 {"profile"=>
   {"username"=>"pakwit",
    "fullname"=>"Patrick Dunnam",
    "location"=>"San Francisco",
    "email"=>"patrick@github.com",
    "link"=>"Joined on Jul 23, 2012",
    "join_date"=>"2012-07-23T20:04:27Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"pamboat",
    "fullname"=>"Pam Lama",
    "location"=>"pamboat@github.com",
    "email"=>"Joined on Dec 2, 2013",
    "link"=>"",
    "join_date"=>"2013-12-02T21:19:08Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"PatrickBM",
    "fullname"=>"Patrick McKenna",
    "location"=>"patrickbm@github.com",
    "email"=>"Joined on Feb 14, 2013",
    "link"=>"",
    "join_date"=>"2013-02-14T00:50:38Z"},
  "stats"=>{"C++"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"peff",
    "fullname"=>"Jeff King",
    "location"=>"Charlottesville, VA",
    "email"=>"peff@peff.net",
    "link"=>"http://peff.net",
    "join_date"=>"2009-01-12T09:29:10Z"},
  "stats"=>
   {"C"=>{"count"=>3, "star"=>17},
    "Perl"=>{"count"=>5, "star"=>33},
    "Java"=>{"count"=>1, "star"=>0},
    "Shell"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"pengwynn",
    "fullname"=>"Wynn Netherland",
    "location"=>"TX",
    "email"=>"http://wynnnetherland.com",
    "link"=>"Joined on Feb 25, 2008",
    "join_date"=>"2008-02-25T18:24:19Z"},
  "stats"=>
   {"Go"=>{"count"=>1, "star"=>487},
    "Ruby"=>{"count"=>37, "star"=>971},
    "CSS"=>{"count"=>2, "star"=>32},
    "JavaScript"=>{"count"=>5, "star"=>186},
    "Shell"=>{"count"=>1, "star"=>5}}},
 {"profile"=>
   {"username"=>"PeterBell",
    "fullname"=>"Peter Bell",
    "location"=>"New York, NY",
    "email"=>"http://roninlabs.io",
    "link"=>"Joined on Apr 4, 2008",
    "join_date"=>"2008-04-04T01:02:09Z"},
  "stats"=>{"CSS"=>{"count"=>1, "star"=>0}, "Shell"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"petros",
    "fullname"=>"Petros Amiridis",
    "location"=>"Thessaloniki, Greece",
    "email"=>"petros@amiridis.net",
    "link"=>"http://amiridis.net",
    "join_date"=>"2008-10-13T21:19:57Z"},
  "stats"=>{"Ruby"=>{"count"=>1, "star"=>3}}},
 {"profile"=>
   {"username"=>"piki",
    "fullname"=>"Patrick Reynolds",
    "location"=>"Pensacola, FL",
    "email"=>"http://piki.org/patrick/",
    "link"=>"Joined on Feb 21, 2013",
    "join_date"=>"2013-02-21T14:17:12Z"},
  "stats"=>
   {"Perl"=>{"count"=>1, "star"=>1},
    "JavaScript"=>{"count"=>1, "star"=>0},
    "Shell"=>{"count"=>1, "star"=>0},
    "C++"=>{"count"=>2, "star"=>0},
    "C"=>{"count"=>2, "star"=>0}}},
 {"profile"=>
   {"username"=>"pjhyett",
    "fullname"=>"PJ Hyett",
    "location"=>"San Francisco",
    "email"=>"pj@github.com",
    "link"=>"http://hyett.com",
    "join_date"=>"2008-01-07T17:54:22Z"},
  "stats"=>
   {"Ruby"=>{"count"=>11, "star"=>619},
    "Python"=>{"count"=>1, "star"=>2},
    "JavaScript"=>{"count"=>1, "star"=>7}}},
 {"profile"=>
   {"username"=>"pmn",
    "fullname"=>"Paul Nakata",
    "location"=>"San Francisco, CA",
    "email"=>"pmn@github.com",
    "link"=>"http://pmn.org",
    "join_date"=>"2010-05-17T16:55:33Z"},
  "stats"=>
   {"Go"=>{"count"=>4, "star"=>1},
    "Ruby"=>{"count"=>1, "star"=>4},
    "Arduino"=>{"count"=>1, "star"=>0},
    "JavaScript"=>{"count"=>3, "star"=>3},
    "Python"=>{"count"=>2, "star"=>2},
    "C#"=>{"count"=>1, "star"=>1},
    "Clojure"=>{"count"=>3, "star"=>16}}},
 {"profile"=>
   {"username"=>"probablycorey",
    "fullname"=>"Corey Johnson",
    "location"=>"San Francisco",
    "email"=>"probablycorey@gmail.com",
    "link"=>"http://probablycorey.com",
    "join_date"=>"2008-02-21T22:07:26Z"},
  "stats"=>
   {"CSS"=>{"count"=>1, "star"=>1},
    "CoffeeScript"=>{"count"=>5, "star"=>14},
    "Ruby"=>{"count"=>3, "star"=>42},
    "JavaScript"=>{"count"=>2, "star"=>1},
    "C"=>{"count"=>2, "star"=>462},
    "Objective-C"=>{"count"=>2, "star"=>32}}},
 {"profile"=>
   {"username"=>"ptoomey3",
    "fullname"=>"Patrick Toomey",
    "location"=>"Denver, CO",
    "email"=>"ptoomey3@biasedcoin.com",
    "link"=>"http://biasedcoin.com",
    "join_date"=>"2009-07-09T19:18:05Z"},
  "stats"=>
   {"C"=>{"count"=>1, "star"=>2},
    "JavaScript"=>{"count"=>1, "star"=>1},
    "Objective-C"=>{"count"=>1, "star"=>200},
    "Ruby"=>{"count"=>2, "star"=>3},
    "Python"=>{"count"=>2, "star"=>19}}},
 {"profile"=>
   {"username"=>"rachelmyers",
    "fullname"=>"Rachel Myers",
    "location"=>"San Francisco, CA",
    "email"=>"rachelmariemyers@gmail.com",
    "link"=>"Joined on Feb 24, 2010",
    "join_date"=>"2010-02-24T04:00:21Z"},
  "stats"=>
   {"CSS"=>{"count"=>1, "star"=>1},
    "Ruby"=>{"count"=>3, "star"=>9},
    "CoffeeScript"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"raganwald",
    "fullname"=>"Reg Braithwaite",
    "location"=>"Toronto, Canada",
    "email"=>"reg@braythwayt.com",
    "link"=>"http://braythwayt.com",
    "join_date"=>"2008-07-21T20:09:46Z"},
  "stats"=>
   {"HTML"=>{"count"=>2, "star"=>10},
    "JavaScript"=>{"count"=>12, "star"=>1186},
    "Java"=>{"count"=>1, "star"=>0},
    "CoffeeScript"=>{"count"=>8, "star"=>577},
    "Ruby"=>{"count"=>1, "star"=>248},
    "C"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"rathjenc",
    "fullname"=>"Chris Rathjen",
    "location"=>"Chicago",
    "email"=>"chris.rathjen@github.com",
    "link"=>"Joined on Jun 13, 2013",
    "join_date"=>"2013-06-13T16:44:13Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"robrix",
    "fullname"=>"Rob Rix",
    "location"=>"London, Ontario",
    "email"=>"rob.rix@github.com",
    "link"=>"http://antitypical.com",
    "join_date"=>"2009-03-03T11:42:59Z"},
  "stats"=>
   {"Swift"=>{"count"=>17, "star"=>544},
    "Objective-C"=>{"count"=>36, "star"=>903},
    "C"=>{"count"=>5, "star"=>87},
    "C++"=>{"count"=>1, "star"=>2},
    "CSS"=>{"count"=>1, "star"=>0},
    "Ruby"=>{"count"=>5, "star"=>19},
    "JavaScript"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"rodjek",
    "fullname"=>"Tim Sharpe",
    "location"=>"Melbourne",
    "email"=>"tim@github.com",
    "link"=>"http://bombasticmonkey.com",
    "join_date"=>"2009-05-04T03:28:14Z"},
  "stats"=>
   {"Ruby"=>{"count"=>29, "star"=>1738},
    "VimL"=>{"count"=>2, "star"=>308},
    "CSS"=>{"count"=>1, "star"=>1},
    "Puppet"=>{"count"=>1, "star"=>10},
    "Augeas"=>{"count"=>1, "star"=>4},
    "Python"=>{"count"=>2, "star"=>15},
    "Shell"=>{"count"=>1, "star"=>0},
    "Erlang"=>{"count"=>1, "star"=>13},
    "JavaScript"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"rsanheim",
    "fullname"=>"Rob Sanheim",
    "location"=>"Madison, WI, NORTH AMERICA",
    "email"=>"https://github.com/rsanheim",
    "link"=>"Joined on Jan 27, 2008",
    "join_date"=>"2008-01-27T07:09:47Z"},
  "stats"=>{"Ruby"=>{"count"=>17, "star"=>197}}},
 {"profile"=>
   {"username"=>"rsese",
    "fullname"=>"Robert Sese",
    "location"=>"Chicago, IL",
    "email"=>"sese@github.com",
    "link"=>"http://www.hellarobots.com",
    "join_date"=>"2011-04-17T01:44:30Z"},
  "stats"=>
   {"Shell"=>{"count"=>1, "star"=>0},
    "CSS"=>{"count"=>2, "star"=>9},
    "JavaScript"=>{"count"=>2, "star"=>2},
    "Ruby"=>{"count"=>1, "star"=>3},
    "PHP"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"rtomayko",
    "fullname"=>"Ryan Tomayko",
    "location"=>"Cleveland, OH",
    "email"=>"ryan@github.com",
    "link"=>"http://tomayko.com",
    "join_date"=>"2008-02-19T03:30:53Z"},
  "stats"=>
   {"Ruby"=>{"count"=>16, "star"=>3799},
    "Perl"=>{"count"=>1, "star"=>154},
    "VimL"=>{"count"=>1, "star"=>506},
    "Shell"=>{"count"=>2, "star"=>730},
    "JavaScript"=>{"count"=>1, "star"=>1},
    "C"=>{"count"=>2, "star"=>51}}},
 {"profile"=>
   {"username"=>"rubiojr",
    "fullname"=>"Sergio Rubio",
    "location"=>"Barcelona, Spain",
    "email"=>"sergio.rubio@github.com",
    "link"=>"http://rubiojr.rbel.co",
    "join_date"=>"2008-05-21T07:53:58Z"},
  "stats"=>
   {"Go"=>{"count"=>5, "star"=>0},
    "Ruby"=>{"count"=>64, "star"=>306},
    "Shell"=>{"count"=>10, "star"=>13},
    "Makefile"=>{"count"=>1, "star"=>1},
    "C"=>{"count"=>4, "star"=>24},
    "JavaScript"=>{"count"=>1, "star"=>0},
    "Python"=>{"count"=>3, "star"=>3},
    "CSS"=>{"count"=>1, "star"=>1},
    "Puppet"=>{"count"=>1, "star"=>0},
    "Objective-C"=>{"count"=>1, "star"=>6}}},
 {"profile"=>
   {"username"=>"rubyist",
    "fullname"=>"Scott Barron",
    "location"=>"Ohio",
    "email"=>"scott.barron@github.com",
    "link"=>"http://rubyi.st",
    "join_date"=>"2008-02-05T15:03:25Z"},
  "stats"=>
   {"Go"=>{"count"=>10, "star"=>228},
    "Ruby"=>{"count"=>15, "star"=>137},
    "CoffeeScript"=>{"count"=>3, "star"=>19},
    "C"=>{"count"=>2, "star"=>5},
    "Arduino"=>{"count"=>1, "star"=>0},
    "JavaScript"=>{"count"=>6, "star"=>12},
    "Objective-C"=>{"count"=>4, "star"=>40}}},
 {"profile"=>
   {"username"=>"sachinr",
    "fullname"=>"Sachin Ranchod",
    "location"=>"San Francisco",
    "email"=>"sachin.ranchod@gmail.com",
    "link"=>"Joined on Mar 30, 2011",
    "join_date"=>"2011-03-30T20:44:28Z"},
  "stats"=>
   {"JavaScript"=>{"count"=>2, "star"=>0},
    "Ruby"=>{"count"=>6, "star"=>4},
    "CoffeeScript"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"samlambert",
    "fullname"=>"Sam Lambert",
    "location"=>"Newcastle Upon Tyne, UK",
    "email"=>"http://samlambert.com",
    "link"=>"Joined on Oct 27, 2011",
    "join_date"=>"2011-10-27T14:26:25Z"},
  "stats"=>
   {"Ruby"=>{"count"=>2, "star"=>13},
    "CoffeeScript"=>{"count"=>2, "star"=>51},
    "Perl"=>{"count"=>1, "star"=>4}}},
 {"profile"=>
   {"username"=>"sarapyle",
    "fullname"=>"Sara",
    "location"=>"Joined on Jul 16, 2012",
    "email"=>"",
    "link"=>"",
    "join_date"=>"2012-07-16T14:35:15Z"},
  "stats"=>{"CSS"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"sbryant",
    "fullname"=>"Sean Bryant",
    "location"=>"San Francisco, CA",
    "email"=>"sbryant@github.com",
    "link"=>"http://www.thinkingofbryant.com",
    "join_date"=>"2008-04-15T22:31:55Z"},
  "stats"=>
   {"C"=>{"count"=>3, "star"=>1},
    "CoffeeScript"=>{"count"=>1, "star"=>1},
    "Ruby"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"ScarlettSparks",
    "fullname"=>"Sparks",
    "location"=>"Joined on Sep 26, 2012",
    "email"=>"",
    "link"=>"",
    "join_date"=>"2012-09-26T14:31:37Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"schacon",
    "fullname"=>"Scott Chacon",
    "location"=>"San Francisco, CA",
    "email"=>"schacon@gmail.com",
    "link"=>"http://scottchacon.com",
    "join_date"=>"2008-01-27T17:19:28Z"},
  "stats"=>
   {"Python"=>{"count"=>8, "star"=>556},
    "Ruby"=>{"count"=>67, "star"=>3523},
    "CoffeeScript"=>{"count"=>2, "star"=>6},
    "Arduino"=>{"count"=>1, "star"=>1},
    "XSLT"=>{"count"=>1, "star"=>1},
    "JavaScript"=>{"count"=>18, "star"=>190},
    "CSS"=>{"count"=>1, "star"=>2},
    "C"=>{"count"=>13, "star"=>171},
    "Objective-C"=>{"count"=>7, "star"=>269},
    "Shell"=>{"count"=>4, "star"=>229},
    "PHP"=>{"count"=>1, "star"=>7},
    "Haxe"=>{"count"=>1, "star"=>5},
    "Java"=>{"count"=>3, "star"=>10},
    "C++"=>{"count"=>2, "star"=>10},
    "Erlang"=>{"count"=>2, "star"=>65},
    "ActionScript"=>{"count"=>1, "star"=>38},
    "C#"=>{"count"=>1, "star"=>6}}},
 {"profile"=>
   {"username"=>"scottbuxton",
    "fullname"=>"Scott Buxton",
    "location"=>"scott.buxton@github.com",
    "email"=>"Joined on May 6, 2013",
    "link"=>"",
    "join_date"=>"2013-05-06T17:13:11Z"},
  "stats"=>{"Ruby"=>{"count"=>2, "star"=>0}, "CSS"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"scottjg",
    "fullname"=>"Scott J. Goldman",
    "location"=>"San Francisco",
    "email"=>"scottjg@github.com",
    "link"=>"http://twitter.com/scottjg",
    "join_date"=>"2009-08-23T01:28:09Z"},
  "stats"=>
   {"C"=>{"count"=>9, "star"=>37},
    "Go"=>{"count"=>1, "star"=>1},
    "Ruby"=>{"count"=>2, "star"=>0},
    "CoffeeScript"=>{"count"=>1, "star"=>2},
    "JavaScript"=>{"count"=>1, "star"=>5}}},
 {"profile"=>
   {"username"=>"searls",
    "fullname"=>"Justin Searls",
    "location"=>"Columbus, OH",
    "email"=>"justin@testdouble.com",
    "link"=>"http://about.me/searls",
    "join_date"=>"2009-04-29T20:23:34Z"},
  "stats"=>
   {"JavaScript"=>{"count"=>44, "star"=>754},
    "Ruby"=>{"count"=>20, "star"=>134},
    "Java"=>{"count"=>4, "star"=>285},
    "CoffeeScript"=>{"count"=>4, "star"=>184},
    "Python"=>{"count"=>1, "star"=>2},
    "Lua"=>{"count"=>1, "star"=>1},
    "Objective-J"=>{"count"=>1, "star"=>2},
    "Objective-C"=>{"count"=>1, "star"=>25}}},
 {"profile"=>
   {"username"=>"shawndavenport",
    "fullname"=>"Shawn Davenport",
    "location"=>"Baton Rouge, LA",
    "email"=>"http://twitter.com/nothingstrivial",
    "link"=>"Joined on Feb 21, 2010",
    "join_date"=>"2010-02-21T21:32:48Z"},
  "stats"=>{"HTML"=>{"count"=>1, "star"=>0}, "Ruby"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"shayfrendt",
    "fullname"=>"Shay Frendt",
    "location"=>"Raleigh, NC",
    "email"=>"shay@github.com",
    "link"=>"Joined on Nov 4, 2008",
    "join_date"=>"2008-11-04T03:03:10Z"},
  "stats"=>
   {"Ruby"=>{"count"=>4, "star"=>7},
    "VimL"=>{"count"=>1, "star"=>5},
    "JavaScript"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"shiftkey",
    "fullname"=>"Brendan Forster",
    "location"=>"Sydney, Australia",
    "email"=>"brendan@github.com",
    "link"=>"http://brendanforster.com",
    "join_date"=>"2010-08-10T00:33:01Z"},
  "stats"=>
   {"C#"=>{"count"=>33, "star"=>165},
    "CSS"=>{"count"=>1, "star"=>1},
    "Shell"=>{"count"=>3, "star"=>4},
    "JavaScript"=>{"count"=>7, "star"=>28},
    "PowerShell"=>{"count"=>1, "star"=>2},
    "C++"=>{"count"=>2, "star"=>6}}},
 {"profile"=>
   {"username"=>"simonsj",
    "fullname"=>"Jon Simons",
    "location"=>"Joined on Aug 23, 2009",
    "email"=>"",
    "link"=>"",
    "join_date"=>"2009-08-23T03:53:28Z"},
  "stats"=>
   {"C"=>{"count"=>4, "star"=>3},
    "VimL"=>{"count"=>1, "star"=>1},
    "Shell"=>{"count"=>1, "star"=>1},
    "Vala"=>{"count"=>1, "star"=>3}}},
 {"profile"=>
   {"username"=>"skalnik",
    "fullname"=>"Mike Skalnik",
    "location"=>"San Francisco, CA",
    "email"=>"skalnik@github.com",
    "link"=>"http://mikeskalnik.com",
    "join_date"=>"2008-03-07T21:40:04Z"},
  "stats"=>
   {"VimL"=>{"count"=>2, "star"=>157},
    "HTML"=>{"count"=>1, "star"=>0},
    "JavaScript"=>{"count"=>7, "star"=>16},
    "Arduino"=>{"count"=>2, "star"=>1},
    "CoffeeScript"=>{"count"=>2, "star"=>1},
    "Shell"=>{"count"=>1, "star"=>2},
    "Ruby"=>{"count"=>18, "star"=>39},
    "C"=>{"count"=>4, "star"=>4},
    "Objective-C"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"southgate",
    "fullname"=>"Alex Southgate",
    "location"=>"San Francisco, CA",
    "email"=>"alex.southgate@github.com",
    "link"=>"http://2ndrategeniuses.com",
    "join_date"=>"2009-02-08T19:01:17Z"},
  "stats"=>
   {"Ruby"=>{"count"=>2, "star"=>2},
    "Shell"=>{"count"=>1, "star"=>1},
    "Python"=>{"count"=>3, "star"=>4},
    "JavaScript"=>{"count"=>3, "star"=>1}}},
 {"profile"=>
   {"username"=>"spicycode",
    "fullname"=>"Chad Humphries",
    "location"=>"Columbus, OH",
    "email"=>"chad@github.com",
    "link"=>"Joined on Feb 13, 2008",
    "join_date"=>"2008-02-13T13:57:32Z"},
  "stats"=>
   {"VimL"=>{"count"=>3, "star"=>139},
    "Shell"=>{"count"=>2, "star"=>124},
    "ApacheConf"=>{"count"=>1, "star"=>0},
    "CSS"=>{"count"=>1, "star"=>1},
    "Ruby"=>{"count"=>7, "star"=>218}}},
 {"profile"=>
   {"username"=>"spraints",
    "fullname"=>"Matt Burke",
    "location"=>"Indiana, USA",
    "email"=>"http://pickardayune.com/",
    "link"=>"Joined on Aug 9, 2008",
    "join_date"=>"2008-08-09T22:49:47Z"},
  "stats"=>
   {"Ruby"=>{"count"=>33, "star"=>76},
    "Lua"=>{"count"=>1, "star"=>0},
    "ApacheConf"=>{"count"=>1, "star"=>0},
    "CSS"=>{"count"=>3, "star"=>6},
    "C#"=>{"count"=>6, "star"=>51},
    "C"=>{"count"=>6, "star"=>0},
    "Java"=>{"count"=>2, "star"=>2},
    "Python"=>{"count"=>2, "star"=>0},
    "JavaScript"=>{"count"=>4, "star"=>5},
    "Go"=>{"count"=>1, "star"=>0},
    "CoffeeScript"=>{"count"=>1, "star"=>2},
    "Shell"=>{"count"=>2, "star"=>2},
    "Objective-C"=>{"count"=>2, "star"=>4}}},
 {"profile"=>
   {"username"=>"sroberts",
    "fullname"=>"Scott J. Roberts",
    "location"=>"Columbus, OH",
    "email"=>"http://sroberts.github.io",
    "link"=>"Joined on Jan 7, 2009",
    "join_date"=>"2009-01-07T07:14:26Z"},
  "stats"=>
   {"CSS"=>{"count"=>2, "star"=>2},
    "Python"=>{"count"=>9, "star"=>87},
    "CoffeeScript"=>{"count"=>1, "star"=>28},
    "Shell"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"sshirokov",
    "fullname"=>"Yaroslav Shirokov",
    "location"=>"San Francisco, CA",
    "email"=>"slava@github.com",
    "link"=>"https://twitter.com/sshirokov",
    "join_date"=>"2008-12-13T00:45:26Z"},
  "stats"=>
   {"CSS"=>{"count"=>1, "star"=>0},
    "C"=>{"count"=>3, "star"=>65},
    "Ruby"=>{"count"=>1, "star"=>0},
    "CoffeeScript"=>{"count"=>2, "star"=>2},
    "JavaScript"=>{"count"=>8, "star"=>32},
    "Shell"=>{"count"=>1, "star"=>2},
    "Python"=>{"count"=>6, "star"=>16}}},
 {"profile"=>
   {"username"=>"stevekrause",
    "fullname"=>"Steve Krause",
    "location"=>"Mountain View, CA",
    "email"=>"steve.krause@github.com",
    "link"=>"Joined on Oct 16, 2013",
    "join_date"=>"2013-10-16T03:15:17Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"steveward",
    "fullname"=>"Steve Ward",
    "location"=>"ward@github.com",
    "email"=>"Joined on Apr 11, 2011",
    "link"=>"",
    "join_date"=>"2011-04-11T03:11:36Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"sundaykofax",
    "fullname"=>"Sonya Green",
    "location"=>"http://www.outsidecat.com",
    "email"=>"Joined on Sep 16, 2011",
    "link"=>"",
    "join_date"=>"2011-09-16T00:45:12Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"talniv",
    "fullname"=>"Tal Niv",
    "location"=>"San Francisco",
    "email"=>"tal.niv@github.com",
    "link"=>"Joined on Aug 6, 2013",
    "join_date"=>"2013-08-06T21:38:02Z"},
  "stats"=>{"PHP"=>{"count"=>1, "star"=>0}, "CSS"=>{"count"=>1, "star"=>0}}},
 {"profile"=>
   {"username"=>"tclem",
    "fullname"=>"Timothy Clem",
    "location"=>"San Francisco",
    "email"=>"timothy.clem@gmail.com",
    "link"=>"http://adaptivepatchwork.com",
    "join_date"=>"2009-10-07T20:26:53Z"},
  "stats"=>
   {"Shell"=>{"count"=>1, "star"=>4},
    "CSS"=>{"count"=>1, "star"=>7},
    "CoffeeScript"=>{"count"=>1, "star"=>1},
    "VimL"=>{"count"=>1, "star"=>89},
    "Java"=>{"count"=>1, "star"=>2},
    "C#"=>{"count"=>2, "star"=>20},
    "C"=>{"count"=>1, "star"=>2},
    "Objective-C"=>{"count"=>1, "star"=>2},
    "Ruby"=>{"count"=>2, "star"=>5}}},
 {"profile"=>
   {"username"=>"technicalpickles",
    "fullname"=>"Josh Nichols",
    "location"=>"Savannah, GA",
    "email"=>"josh@technicalpickles.com",
    "link"=>"http://technicalpickles.com",
    "join_date"=>"2008-02-07T05:38:06Z"},
  "stats"=>
   {"VimL"=>{"count"=>1, "star"=>30},
    "JavaScript"=>{"count"=>6, "star"=>20},
    "CoffeeScript"=>{"count"=>1, "star"=>0},
    "Ruby"=>{"count"=>82, "star"=>734},
    "Shell"=>{"count"=>5, "star"=>15},
    "CSS"=>{"count"=>1, "star"=>3},
    "Python"=>{"count"=>1, "star"=>3}}},
 {"profile"=>
   {"username"=>"technoweenie",
    "fullname"=>"risk danger olson",
    "location"=>"Louisville, CO",
    "email"=>"technoweenie@gmail.com",
    "link"=>"http://techno-weenie.net",
    "join_date"=>"2008-01-14T04:33:35Z"},
  "stats"=>
   {"CoffeeScript"=>{"count"=>11, "star"=>832},
    "Ruby"=>{"count"=>64, "star"=>2695},
    "Go"=>{"count"=>10, "star"=>191},
    "CSS"=>{"count"=>1, "star"=>1},
    "JavaScript"=>{"count"=>17, "star"=>825},
    "Elixir"=>{"count"=>1, "star"=>3},
    "Python"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"tekkub",
    "fullname"=>"Tekkub",
    "location"=>"Denver, CO",
    "email"=>"code@tekkub.net",
    "link"=>"http://tekkub.net",
    "join_date"=>"2008-02-23T21:14:45Z"},
  "stats"=>
   {"Lua"=>{"count"=>5, "star"=>239},
    "HTML"=>{"count"=>1, "star"=>49},
    "CoffeeScript"=>{"count"=>2, "star"=>21},
    "JavaScript"=>{"count"=>3, "star"=>11},
    "Ruby"=>{"count"=>2, "star"=>2},
    "Python"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"thedaniel",
    "fullname"=>"Daniel Hengeveld",
    "location"=>"Los Angeles, CA",
    "email"=>"danielwh@gmail.com",
    "link"=>"http://neoglam.com",
    "join_date"=>"2008-02-28T07:42:30Z"},
  "stats"=>
   {"CoffeeScript"=>{"count"=>3, "star"=>7},
    "Ruby"=>{"count"=>2, "star"=>11},
    "Shell"=>{"count"=>1, "star"=>0},
    "CSS"=>{"count"=>1, "star"=>0},
    "JavaScript"=>{"count"=>1, "star"=>1},
    "Python"=>{"count"=>2, "star"=>6}}},
 {"profile"=>
   {"username"=>"tjl2",
    "fullname"=>"Tim Littlemore",
    "location"=>"Cheshire, UK",
    "email"=>"tim.littlemore@github.com",
    "link"=>"Joined on Jan 11, 2010",
    "join_date"=>"2010-01-11T22:02:14Z"},
  "stats"=>
   {"Ruby"=>{"count"=>19, "star"=>37},
    "Shell"=>{"count"=>3, "star"=>3},
    "Python"=>{"count"=>1, "star"=>2},
    "JavaScript"=>{"count"=>1, "star"=>1}}},
 {"profile"=>
   {"username"=>"tmm1",
    "fullname"=>"Aman Gupta",
    "location"=>"San Francisco, CA",
    "email"=>"aman@tmm1.net",
    "link"=>"http://twitter.com/tmm1",
    "join_date"=>"2008-03-08T02:10:31Z"},
  "stats"=>
   {"Ruby"=>{"count"=>42, "star"=>3486},
    "C"=>{"count"=>17, "star"=>2271},
    "CSS"=>{"count"=>1, "star"=>3},
    "JavaScript"=>{"count"=>7, "star"=>293},
    "C++"=>{"count"=>3, "star"=>12},
    "Shell"=>{"count"=>1, "star"=>2},
    "Python"=>{"count"=>2, "star"=>295},
    "VimL"=>{"count"=>2, "star"=>4}}},
 {"profile"=>
   {"username"=>"tnm",
    "fullname"=>"Ted Nyman",
    "location"=>"California",
    "email"=>"ted@ted.io",
    "link"=>"http://ted.io",
    "join_date"=>"2009-09-14T19:28:01Z"},
  "stats"=>
   {"Ruby"=>{"count"=>3, "star"=>228},
    "Java"=>{"count"=>3, "star"=>37},
    "C"=>{"count"=>8, "star"=>70},
    "Python"=>{"count"=>6, "star"=>169},
    "Shell"=>{"count"=>1, "star"=>18},
    "Scala"=>{"count"=>3, "star"=>23},
    "JavaScript"=>{"count"=>1, "star"=>10},
    "Erlang"=>{"count"=>1, "star"=>4},
    "Lua"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"tonyjaramillo",
    "fullname"=>"Tony Jaramillo",
    "location"=>"San Francisco, CA",
    "email"=>"tony@github.com",
    "link"=>"Joined on Jan 3, 2012",
    "join_date"=>"2012-01-03T01:31:56Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"TwP",
    "fullname"=>"Tim Pease",
    "location"=>"Boulder, CO",
    "email"=>"tim.pease@gmail.com",
    "link"=>"http://pea53.com",
    "join_date"=>"2008-04-10T21:53:10Z"},
  "stats"=>
   {"VimL"=>{"count"=>1, "star"=>2},
    "Ruby"=>{"count"=>25, "star"=>1140},
    "C"=>{"count"=>2, "star"=>5},
    "CSS"=>{"count"=>1, "star"=>1},
    "JavaScript"=>{"count"=>2, "star"=>12},
    "Tcl"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"vladoherman",
    "fullname"=>"Vlado Herman",
    "location"=>"San Francisco",
    "email"=>"Joined on Dec 1, 2012",
    "link"=>"",
    "join_date"=>"2012-12-01T00:38:46Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"vmg",
    "fullname"=>"Vicent Marti",
    "location"=>"Europe",
    "email"=>"vicent@github.com",
    "link"=>"http://twitter.com/vmg",
    "join_date"=>"2008-12-26T20:21:00Z"},
  "stats"=>
   {"C"=>{"count"=>21, "star"=>1132},
    "Go"=>{"count"=>1, "star"=>1},
    "Python"=>{"count"=>2, "star"=>1},
    "JavaScript"=>{"count"=>2, "star"=>11},
    "Ruby"=>{"count"=>1, "star"=>3}}},
 {"profile"=>
   {"username"=>"VxJasonxV",
    "fullname"=>"Jason Salaz",
    "location"=>"Castle Rock, CO, USA",
    "email"=>"jsalaz@github.com",
    "link"=>"Joined on Mar 1, 2008",
    "join_date"=>"2008-03-01T18:42:49Z"},
  "stats"=>
   {"Ruby"=>{"count"=>2, "star"=>1},
    "Perl"=>{"count"=>1, "star"=>7},
    "JavaScript"=>{"count"=>1, "star"=>2}}},
 {"profile"=>
   {"username"=>"whitmonaq",
    "fullname"=>"Whitney Naquin",
    "location"=>"Joined on Jun 23, 2013",
    "email"=>"",
    "link"=>"",
    "join_date"=>"2013-06-23T00:21:40Z"},
  "stats"=>{}},
 {"profile"=>
   {"username"=>"ymendel",
    "fullname"=>"Yossef Mendelssohn",
    "location"=>"ymendel@pobox.com",
    "email"=>"Joined on Feb 21, 2008",
    "link"=>"",
    "join_date"=>"2008-02-21T22:09:30Z"},
  "stats"=>
   {"Shell"=>{"count"=>1, "star"=>9},
    "Ruby"=>{"count"=>11, "star"=>163},
    "CoffeeScript"=>{"count"=>1, "star"=>6},
    "JavaScript"=>{"count"=>3, "star"=>1}}},
 {"profile"=>
   {"username"=>"zcbenz",
    "fullname"=>"Cheng Zhao",
    "location"=>"Beijing",
    "email"=>"zcbenz@github.com",
    "link"=>"http://cheng.guru",
    "join_date"=>"2011-02-26T14:16:12Z"},
  "stats"=>
   {"HTML"=>{"count"=>1, "star"=>8},
    "C++"=>{"count"=>10, "star"=>228},
    "JavaScript"=>{"count"=>7, "star"=>64},
    "Perl"=>{"count"=>1, "star"=>5},
    "AutoHotkey"=>{"count"=>1, "star"=>1},
    "C"=>{"count"=>1, "star"=>2},
    "C#"=>{"count"=>1, "star"=>2},
    "Ruby"=>{"count"=>1, "star"=>6},
    "Shell"=>{"count"=>1, "star"=>2},
    "PHP"=>{"count"=>1, "star"=>4}}},
 {"profile"=>
   {"username"=>"zerowidth",
    "fullname"=>"Nathan Witmer",
    "location"=>"Boulder, CO",
    "email"=>"nathan@zerowidth.com",
    "link"=>"http://zerowidth.com",
    "join_date"=>"2008-03-27T17:19:22Z"},
  "stats"=>
   {"C"=>{"count"=>1, "star"=>0},
    "Ruby"=>{"count"=>19, "star"=>434},
    "VimL"=>{"count"=>3, "star"=>53},
    "CoffeeScript"=>{"count"=>2, "star"=>25},
    "Clojure"=>{"count"=>3, "star"=>5},
    "Shell"=>{"count"=>1, "star"=>8},
    "JavaScript"=>{"count"=>4, "star"=>8}}}]
end